//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccreditationAndCertificationDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AccreditationAndCertificationDetail()
        {
            this.AccreditationAndCertificationDocuments = new HashSet<AccreditationAndCertificationDocument>();
        }
    
        public int Id { get; set; }
        public int ApplicationId { get; set; }
        public string Accreditationboard { get; set; }
        public string AccreditationLevelOrType { get; set; }
        public string AccreditationCertificationNo { get; set; }
        public Nullable<System.DateTime> IssuedDate { get; set; }
        public Nullable<System.DateTime> ValidUpto { get; set; }
    
        public virtual Application Application { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccreditationAndCertificationDocument> AccreditationAndCertificationDocuments { get; set; }
    }
}
