//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccreditationFee
    {
        public int ID { get; set; }
        public int ApplicationTypeID { get; set; }
        public string Size { get; set; }
        public int ApplicationFees { get; set; }
        public Nullable<int> AnnualFees { get; set; }
        public Nullable<decimal> ServiceTax { get; set; }
        public string VirtualAssessmentFee { get; set; }
        public string FocusAssessmentFee { get; set; }
        public string ReCertificateScopeFee { get; set; }
        public string ReCertificateandScopeFee { get; set; }
    
        public virtual ApplicationType ApplicationType { get; set; }
    }
}
