//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccreditationFeesActive
    {
        public int id { get; set; }
        public Nullable<int> AccreditationFeesID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> Lower_Limit { get; set; }
        public Nullable<int> Upper_Limit { get; set; }
    }
}
