//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccreditationTime
    {
        public int ID { get; set; }
        public int ApplicationID { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string CertificateName { get; set; }
        public string Path { get; set; }
        public string URL { get; set; }
        public string Code { get; set; }
        public Nullable<System.DateTime> Uploaddate { get; set; }
    
        public virtual Application Application { get; set; }
    }
}
