//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Action
    {
        public int ID { get; set; }
        public string ApplicationID { get; set; }
        public string ApplicantID { get; set; }
        public string Remark { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string Updatedby { get; set; }
    
        public virtual Action Action1 { get; set; }
        public virtual Action Action2 { get; set; }
    }
}
