//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Announcement
    {
        public int ProgID { get; set; }
        public string Programmes { get; set; }
        public string link { get; set; }
        public Nullable<bool> display { get; set; }
        public string image_path { get; set; }
        public string Active { get; set; }
        public Nullable<bool> Archieve { get; set; }
        public Nullable<bool> NewAnnouncement { get; set; }
        public string Announcement_Cat { get; set; }
    }
}
