//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class APIAuditLog
    {
        public long Id { get; set; }
        public Nullable<int> ApiUserId { get; set; }
        public string Url { get; set; }
        public string HttpMethod { get; set; }
        public string IPAddress { get; set; }
        public Nullable<int> StatusCode { get; set; }
        public Nullable<System.DateTime> RequestTime { get; set; }
    
        public virtual ApiUser ApiUser { get; set; }
    }
}
