//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppealsDetail
    {
        public int ID { get; set; }
        public int ApplicationID { get; set; }
        public string Details { get; set; }
        public Nullable<bool> Forwarded { get; set; }
        public Nullable<bool> ReadyForReview { get; set; }
        public Nullable<bool> Closed { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
