//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationCurrentStatu
    {
        public int ID { get; set; }
        public int ApplicationID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual ApplicationStatu ApplicationStatu { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
