//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationAccCriteria
    {
        public int ID { get; set; }
        public int ApplicationTypeID { get; set; }
        public string Size { get; set; }
        public string AccreditationCriteria { get; set; }
        public Nullable<int> Days { get; set; }
    
        public virtual ApplicationType ApplicationType { get; set; }
    }
}
