//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application_RenewalStatus
    {
        public int ID { get; set; }
        public Nullable<int> ApplicationID { get; set; }
        public Nullable<int> PrevAppID { get; set; }
        public Nullable<int> FirstAppID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<bool> Renewal { get; set; }
    }
}
