//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Application()
        {
            this.AccreditationTimes = new HashSet<AccreditationTime>();
            this.ReferenceCodes = new HashSet<ReferenceCode>();
            this.SelfAssessmentAttachments = new HashSet<SelfAssessmentAttachment>();
            this.SelfAssessmentOtherValues = new HashSet<SelfAssessmentOtherValue>();
            this.SelfAssessmentValues = new HashSet<SelfAssessmentValue>();
            this.ApplicationTimeLines = new HashSet<ApplicationTimeLine>();
            this.VerifiedDocNumbers = new HashSet<VerifiedDocNumber>();
            this.HospitalNumberOfBeds = new HashSet<HospitalNumberOfBed>();
            this.HospitalOthersBedInformations = new HashSet<HospitalOthersBedInformation>();
            this.ABPMJAYScoreSheetRights = new HashSet<ABPMJAYScoreSheetRight>();
            this.AccreditationAndCertificationDetails = new HashSet<AccreditationAndCertificationDetail>();
            this.AERBApprovalDetails = new HashSet<AERBApprovalDetail>();
            this.AllopathicClinicsApplications = new HashSet<AllopathicClinicsApplication>();
            this.AllopathicClinicsApplications1 = new HashSet<AllopathicClinicsApplication>();
            this.ApplicationCurrentStatus = new HashSet<ApplicationCurrentStatu>();
            this.ApplicationEditPermissions = new HashSet<ApplicationEditPermission>();
            this.DiagnosticEquipValues = new HashSet<DiagnosticEquipValue>();
            this.AssessorNonComplianceObservations = new HashSet<AssessorNonComplianceObservation>();
            this.AyurvedaApplications = new HashSet<AyurvedaApplication>();
            this.DeficienciesReports = new HashSet<DeficienciesReport>();
            this.HomeopathyApplications = new HashSet<HomeopathyApplication>();
            this.HospitalEntryLevels = new HashSet<HospitalEntryLevel>();
            this.HospitalEntryLevels1 = new HashSet<HospitalEntryLevel>();
            this.NabhAttachments = new HashSet<NabhAttachment>();
            this.Panchakarmaapplications = new HashSet<Panchakarmaapplication>();
            this.PHCServices = new HashSet<PHCService>();
            this.PreAssessmentReportValues = new HashSet<PreAssessmentReportValue>();
            this.ReviewRemarks = new HashSet<ReviewRemark>();
            this.shco_app = new HashSet<shco_app>();
            this.SiddhaApplications = new HashSet<SiddhaApplication>();
            this.tblAyurveda_Clinical = new HashSet<tblAyurveda_Clinical>();
            this.UnaniApplications = new HashSet<UnaniApplication>();
            this.YogaApplications = new HashSet<YogaApplication>();
            this.ARTClinicsApplications = new HashSet<ARTClinicsApplication>();
            this.AssessorBloodBankNCs = new HashSet<AssessorBloodBankNC>();
            this.AssessorConfidentialities = new HashSet<AssessorConfidentiality>();
            this.AssessorNonComplianceObservations1 = new HashSet<AssessorNonComplianceObservation>();
            this.BankDetailsOffLinePayments = new HashSet<BankDetailsOffLinePayment>();
            this.BloodBankApplications = new HashSet<BloodBankApplication>();
            this.BloodBankTypeValues = new HashSet<BloodBankTypeValue>();
            this.BloodStorageCentreApplications = new HashSet<BloodStorageCentreApplication>();
            this.BloodStorageCentreAssociatedWithBloodBanks = new HashSet<BloodStorageCentreAssociatedWithBloodBank>();
            this.BloodStorageCentreTypeValues = new HashSet<BloodStorageCentreTypeValue>();
            this.CareHomeApplications = new HashSet<CareHomeApplication>();
            this.CHCApplications = new HashSet<CHCApplication>();
            this.CHCServices = new HashSet<CHCService>();
            this.ClinicalServiceValues = new HashSet<ClinicalServiceValue>();
            this.ClinicTypeValues = new HashSet<ClinicTypeValue>();
            this.ContactPersons = new HashSet<ContactPerson>();
            this.CRSchemeApplications = new HashSet<CRSchemeApplication>();
            this.CustomerDatas = new HashSet<CustomerData>();
            this.DaysWorkingHours = new HashSet<DaysWorkingHour>();
            this.LaboratoryEquipments = new HashSet<LaboratoryEquipment>();
            this.DentalEquipments = new HashSet<DentalEquipment>();
            this.DentalClinicsApplications = new HashSet<DentalClinicsApplication>();
            this.DentalOutDepartments = new HashSet<DentalOutDepartment>();
            this.LaboratoryPersonnels = new HashSet<LaboratoryPersonnel>();
            this.LaboratoryTests = new HashSet<LaboratoryTest>();
            this.EmergencyApplications = new HashSet<EmergencyApplication>();
            this.Equipments = new HashSet<Equipment>();
            this.Equipments2 = new HashSet<Equipments2>();
            this.EquipmentsMIS = new HashSet<EquipmentsMI>();
            this.ExtraDocuments = new HashSet<ExtraDocument>();
            this.FinalAssessmentReports = new HashSet<FinalAssessmentReport>();
            this.FOGSIApplications = new HashSet<FOGSIApplication>();
            this.GroupDiscounts = new HashSet<GroupDiscount>();
            this.HospitalApplications = new HashSet<HospitalApplication>();
            this.InpatientCares = new HashSet<InpatientCare>();
            this.IRCA_CheckPointsValues = new HashSet<IRCA_CheckPointsValues>();
            this.LabServiceValues = new HashSet<LabServiceValue>();
            this.Layouts = new HashSet<Layout>();
            this.LicenseAttachments = new HashSet<LicenseAttachment>();
            this.LicenseValues = new HashSet<LicenseValue>();
            this.ManayataScoreSheetRights = new HashSet<ManayataScoreSheetRight>();
            this.MISApplications = new HashSet<MISApplication>();
            this.MLPApplications = new HashSet<MLPApplication>();
            this.MLPOrganizationCharts = new HashSet<MLPOrganizationChart>();
            this.ModalityValues = new HashSet<ModalityValue>();
            this.MostFrequentDatas = new HashSet<MostFrequentData>();
            this.OPDIPDs = new HashSet<OPDIPD>();
            this.OtherServicesValues = new HashSet<OtherServicesValue>();
            this.OutPatientServices = new HashSet<OutPatientService>();
            this.Participants = new HashSet<Participant>();
            this.PaymentDetails = new HashSet<PaymentDetail>();
            this.PHCApplications = new HashSet<PHCApplication>();
            this.PMJAYApplications = new HashSet<PMJAYApplication>();
            this.PreAssessmentReports = new HashSet<PreAssessmentReport>();
            this.QAPApplications = new HashSet<QAPApplication>();
            this.QAPOtherInfoes = new HashSet<QAPOtherInfo>();
            this.QAPServices = new HashSet<QAPService>();
            this.QAPSpecialities = new HashSet<QAPSpeciality>();
            this.QAPSupportDepts = new HashSet<QAPSupportDept>();
            this.QualityManualAssignedToAssessors = new HashSet<QualityManualAssignedToAssessor>();
            this.QualityManualForwardStatus = new HashSet<QualityManualForwardStatu>();
            this.QualityManualReports = new HashSet<QualityManualReport>();
            this.RemarkByACMembers = new HashSet<RemarkByACMember>();
            this.ReviewUpdates = new HashSet<ReviewUpdate>();
            this.SaveDigitalHealthApplicantLists = new HashSet<SaveDigitalHealthApplicantList>();
            this.ScopeCertificationValues = new HashSet<ScopeCertificationValue>();
            this.ScopeServiceValues = new HashSet<ScopeServiceValue>();
            this.ScopeValues = new HashSet<ScopeValue>();
            this.ServiceAreas = new HashSet<ServiceArea>();
            this.SHCOApplications = new HashSet<SHCOApplication>();
            this.StaffInformation_BB = new HashSet<StaffInformation_BB>();
            this.StaffInformationAttachments = new HashSet<StaffInformationAttachment>();
            this.StaffInformationMLPs = new HashSet<StaffInformationMLP>();
            this.StaffInformationValues = new HashSet<StaffInformationValue>();
            this.StaffInformationValueEyes = new HashSet<StaffInformationValueEye>();
            this.StrokeApplications = new HashSet<StrokeApplication>();
            this.SupportDepartmentValues = new HashSet<SupportDepartmentValue>();
            this.SurveillanceReports = new HashSet<SurveillanceReport>();
            this.TrainingApplications = new HashSet<TrainingApplication>();
            this.WCServices = new HashSet<WCService>();
            this.WellnessCenterApplications = new HashSet<WellnessCenterApplication>();
            this.WorkshopApplications = new HashSet<WorkshopApplication>();
            this.AssessorAssignments = new HashSet<AssessorAssignment>();
            this.PmJayValues = new HashSet<PmJayValue>();
        }
    
        public int ID { get; set; }
        public int ApplicantID { get; set; }
        public int StatusID { get; set; }
        public int ApplicationType { get; set; }
        public System.DateTime ApplicationDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccreditationTime> AccreditationTimes { get; set; }
        public virtual ApplicationStatu ApplicationStatu { get; set; }
        public virtual ApplicationType ApplicationType1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReferenceCode> ReferenceCodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SelfAssessmentAttachment> SelfAssessmentAttachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SelfAssessmentOtherValue> SelfAssessmentOtherValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SelfAssessmentValue> SelfAssessmentValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicationTimeLine> ApplicationTimeLines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VerifiedDocNumber> VerifiedDocNumbers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HospitalNumberOfBed> HospitalNumberOfBeds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HospitalOthersBedInformation> HospitalOthersBedInformations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ABPMJAYScoreSheetRight> ABPMJAYScoreSheetRights { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccreditationAndCertificationDetail> AccreditationAndCertificationDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AERBApprovalDetail> AERBApprovalDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AllopathicClinicsApplication> AllopathicClinicsApplications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AllopathicClinicsApplication> AllopathicClinicsApplications1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicationCurrentStatu> ApplicationCurrentStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicationEditPermission> ApplicationEditPermissions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiagnosticEquipValue> DiagnosticEquipValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssessorNonComplianceObservation> AssessorNonComplianceObservations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AyurvedaApplication> AyurvedaApplications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeficienciesReport> DeficienciesReports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HomeopathyApplication> HomeopathyApplications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HospitalEntryLevel> HospitalEntryLevels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HospitalEntryLevel> HospitalEntryLevels1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NabhAttachment> NabhAttachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Panchakarmaapplication> Panchakarmaapplications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHCService> PHCServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PreAssessmentReportValue> PreAssessmentReportValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReviewRemark> ReviewRemarks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<shco_app> shco_app { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SiddhaApplication> SiddhaApplications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAyurveda_Clinical> tblAyurveda_Clinical { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UnaniApplication> UnaniApplications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YogaApplication> YogaApplications { get; set; }
        public virtual tblUser tblUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARTClinicsApplication> ARTClinicsApplications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssessorBloodBankNC> AssessorBloodBankNCs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssessorConfidentiality> AssessorConfidentialities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssessorNonComplianceObservation> AssessorNonComplianceObservations1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BankDetailsOffLinePayment> BankDetailsOffLinePayments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BloodBankApplication> BloodBankApplications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BloodBankTypeValue> BloodBankTypeValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BloodStorageCentreApplication> BloodStorageCentreApplications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BloodStorageCentreAssociatedWithBloodBank> BloodStorageCentreAssociatedWithBloodBanks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BloodStorageCentreTypeValue> BloodStorageCentreTypeValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CareHomeApplication> CareHomeApplications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHCApplication> CHCApplications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHCService> CHCServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClinicalServiceValue> ClinicalServiceValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClinicTypeValue> ClinicTypeValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContactPerson> ContactPersons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRSchemeApplication> CRSchemeApplications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerData> CustomerDatas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DaysWorkingHour> DaysWorkingHours { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LaboratoryEquipment> LaboratoryEquipments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DentalEquipment> DentalEquipments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DentalClinicsApplication> DentalClinicsApplications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DentalOutDepartment> DentalOutDepartments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LaboratoryPersonnel> LaboratoryPersonnels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LaboratoryTest> LaboratoryTests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmergencyApplication> EmergencyApplications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Equipment> Equipments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Equipments2> Equipments2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipmentsMI> EquipmentsMIS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExtraDocument> ExtraDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FinalAssessmentReport> FinalAssessmentReports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FOGSIApplication> FOGSIApplications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GroupDiscount> GroupDiscounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HospitalApplication> HospitalApplications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InpatientCare> InpatientCares { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IRCA_CheckPointsValues> IRCA_CheckPointsValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LabServiceValue> LabServiceValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Layout> Layouts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LicenseAttachment> LicenseAttachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LicenseValue> LicenseValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManayataScoreSheetRight> ManayataScoreSheetRights { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MISApplication> MISApplications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MLPApplication> MLPApplications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MLPOrganizationChart> MLPOrganizationCharts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ModalityValue> ModalityValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MostFrequentData> MostFrequentDatas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OPDIPD> OPDIPDs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OtherServicesValue> OtherServicesValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OutPatientService> OutPatientServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Participant> Participants { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentDetail> PaymentDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHCApplication> PHCApplications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PMJAYApplication> PMJAYApplications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PreAssessmentReport> PreAssessmentReports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QAPApplication> QAPApplications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QAPOtherInfo> QAPOtherInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QAPService> QAPServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QAPSpeciality> QAPSpecialities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QAPSupportDept> QAPSupportDepts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QualityManualAssignedToAssessor> QualityManualAssignedToAssessors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QualityManualForwardStatu> QualityManualForwardStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QualityManualReport> QualityManualReports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RemarkByACMember> RemarkByACMembers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReviewUpdate> ReviewUpdates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaveDigitalHealthApplicantList> SaveDigitalHealthApplicantLists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScopeCertificationValue> ScopeCertificationValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScopeServiceValue> ScopeServiceValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScopeValue> ScopeValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceArea> ServiceAreas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SHCOApplication> SHCOApplications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StaffInformation_BB> StaffInformation_BB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StaffInformationAttachment> StaffInformationAttachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StaffInformationMLP> StaffInformationMLPs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StaffInformationValue> StaffInformationValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StaffInformationValueEye> StaffInformationValueEyes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StrokeApplication> StrokeApplications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupportDepartmentValue> SupportDepartmentValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SurveillanceReport> SurveillanceReports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrainingApplication> TrainingApplications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WCService> WCServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WellnessCenterApplication> WellnessCenterApplications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkshopApplication> WorkshopApplications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssessorAssignment> AssessorAssignments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PmJayValue> PmJayValues { get; set; }
    }
}
