//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationTimeLine
    {
        public int ID { get; set; }
        public int ApplicationID { get; set; }
        public int ApplicationStageID { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<System.DateTime> OriginalDueDate { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> AssessmentTypeID { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual AssessmentType AssessmentType { get; set; }
        public virtual ApplicationStage ApplicationStage { get; set; }
    }
}
