//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssessorBloodBankNC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AssessorBloodBankNC()
        {
            this.EvidenceAttachmentBloodBanks = new HashSet<EvidenceAttachmentBloodBank>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ComplianceID { get; set; }
        public string NcObservation { get; set; }
        public string ClauseNo { get; set; }
        public string classification { get; set; }
        public string CorrectiveAction { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> ApplicationID { get; set; }
        public Nullable<int> AssessmentTypeID { get; set; }
        public string Status { get; set; }
        public string saveedit { get; set; }
        public Nullable<int> AssessorID { get; set; }
        public Nullable<bool> Cycle { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual AssessmentType AssessmentType { get; set; }
        public virtual AssessorNonCompliance AssessorNonCompliance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EvidenceAttachmentBloodBank> EvidenceAttachmentBloodBanks { get; set; }
    }
}
