//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssessorObservationsRemark
    {
        public int ID { get; set; }
        public Nullable<int> AssessorObservationsID { get; set; }
        public string Observation { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> saveedit { get; set; }
        public Nullable<int> ApplicationID { get; set; }
    
        public virtual AssessorObservation AssessorObservation { get; set; }
    }
}
