//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class assesmentSchedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public assesmentSchedule()
        {
            this.AssessorsRemarks = new HashSet<AssessorsRemark>();
        }
    
        public int ID { get; set; }
        public Nullable<int> AssignmentID { get; set; }
        public string assessmorningfrm { get; set; }
        public string assessmorningto { get; set; }
        public string assessafterfrm { get; set; }
        public string assessafterto { get; set; }
        public string assessopening { get; set; }
        public string assessclosing { get; set; }
        public string AssessmentStandard { get; set; }
        public Nullable<int> ApplicationID { get; set; }
        public Nullable<bool> saveedit { get; set; }
    
        public virtual AssessorAssignment AssessorAssignment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssessorsRemark> AssessorsRemarks { get; set; }
    }
}
