//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssessmentSummary
    {
        public int ID { get; set; }
        public Nullable<int> AssignmentID { get; set; }
        public Nullable<System.DateTime> earlierDate { get; set; }
        public string Purpose { get; set; }
        public string summary { get; set; }
        public Nullable<int> ApplicationID { get; set; }
        public Nullable<bool> saveedit { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> Createdon { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string Introduction { get; set; }
        public string StatutoryCompliances { get; set; }
        public string OutsourcedServices { get; set; }
        public string Infrastructure { get; set; }
        public string Manpower { get; set; }
        public string Training { get; set; }
        public string DocumentationReview { get; set; }
        public string SafetyProgramme { get; set; }
        public string InfectionControl { get; set; }
        public string CQI { get; set; }
        public string ScopeOfServices { get; set; }
        public string CommunityServices { get; set; }
        public string Interviews { get; set; }
        public string JustifiableExclusions { get; set; }
        public string StrengthAreas { get; set; }
        public string AreasForImprovement { get; set; }
        public string OtherInformation { get; set; }
        public string ComparisonAssm { get; set; }
    
        public virtual AssessorAssignment AssessorAssignment { get; set; }
    }
}
