//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssessorObservation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AssessorObservation()
        {
            this.AssessorObservationsRemarks = new HashSet<AssessorObservationsRemark>();
        }
    
        public int ID { get; set; }
        public Nullable<int> AssignmentID { get; set; }
        public Nullable<System.DateTime> AssessorDate { get; set; }
        public string Area { get; set; }
        public string Activity { get; set; }
        public string Auditee { get; set; }
    
        public virtual AssessorAssignment AssessorAssignment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssessorObservationsRemark> AssessorObservationsRemarks { get; set; }
    }
}
