//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssessorsRemark
    {
        public int ID { get; set; }
        public int AssesmentScheduleID { get; set; }
        public int AssessorID { get; set; }
        public string MorningRemarks { get; set; }
        public string AfternoonRemarks { get; set; }
        public System.DateTime DailyDate { get; set; }
    
        public virtual assesmentSchedule assesmentSchedule { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
