//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssessorAssignmentDate
    {
        public int ID { get; set; }
        public Nullable<int> AssignmentID { get; set; }
        public Nullable<System.DateTime> AllotedDate { get; set; }
    
        public virtual AssessorAssignment AssessorAssignment { get; set; }
    }
}
