//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssessorNonComplianceObservation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AssessorNonComplianceObservation()
        {
            this.AssessorEvidenceAttachments = new HashSet<AssessorEvidenceAttachment>();
            this.EvidenceAttachmentOthers = new HashSet<EvidenceAttachmentOther>();
            this.MapAssessorNonComplianceObservationAndScoreSheetValues = new HashSet<MapAssessorNonComplianceObservationAndScoreSheetValue>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ComplianceID { get; set; }
        public string Observation { get; set; }
        public string CorrectiveAction { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> ApplicationID { get; set; }
        public Nullable<int> AssessmentTypeID { get; set; }
        public string Status { get; set; }
        public string saveedit { get; set; }
        public Nullable<int> AssessorID { get; set; }
        public string AssessorRemarks { get; set; }
        public Nullable<bool> Cycle { get; set; }
        public string ReferenceForObjectiveElements { get; set; }
        public Nullable<System.DateTime> Createdon { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual Application Application1 { get; set; }
        public virtual AssessmentType AssessmentType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssessorEvidenceAttachment> AssessorEvidenceAttachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EvidenceAttachmentOther> EvidenceAttachmentOthers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MapAssessorNonComplianceObservationAndScoreSheetValue> MapAssessorNonComplianceObservationAndScoreSheetValues { get; set; }
    }
}
