//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssessorBill
    {
        public int Id { get; set; }
        public Nullable<int> ClaimId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Desc { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public string fileName { get; set; }
        public string fileUrl { get; set; }
        public Nullable<int> ExpenseTypeId { get; set; }
        public string OtherExpense { get; set; }
    
        public virtual AssessorClaim AssessorClaim { get; set; }
    }
}
