//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssessorClaim
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AssessorClaim()
        {
            this.AssessorBills = new HashSet<AssessorBill>();
        }
    
        public int ClaimId { get; set; }
        public Nullable<int> AssessorId { get; set; }
        public string RefNo { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<bool> AllowEdit { get; set; }
        public Nullable<int> AssessmentTypeId { get; set; }
        public string TotalAmountInWords { get; set; }
        public string Address { get; set; }
        public string assessorAccountName { get; set; }
        public string bankName { get; set; }
        public string bankBranch { get; set; }
        public string bankIfsc { get; set; }
        public string bankAccountNo { get; set; }
        public string panNo { get; set; }
        public string ApplicationTypeId { get; set; }
        public string HCOName { get; set; }
        public Nullable<int> cityId { get; set; }
        public Nullable<System.DateTime> fromDate { get; set; }
        public Nullable<System.DateTime> toDate { get; set; }
        public Nullable<int> assignedTo { get; set; }
        public string Remark { get; set; }
        public Nullable<int> ActivityId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public string userRole { get; set; }
        public string FullDayUpto4hr { get; set; }
        public string MeetingTrainingLoctionType { get; set; }
        public string VendorNo { get; set; }
        public Nullable<decimal> miscellaneousAmount { get; set; }
        public string fileName { get; set; }
        public string filePath { get; set; }
        public Nullable<int> reviewCycle { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssessorBill> AssessorBills { get; set; }
        public virtual AssessorClaimStatu AssessorClaimStatu { get; set; }
    }
}
