//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssessmentDataForOtherPortal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AssessmentDataForOtherPortal()
        {
            this.AssignmentDateDataForOtherPortals = new HashSet<AssignmentDateDataForOtherPortal>();
        }
    
        public int AssignmentID { get; set; }
        public string RefNo { get; set; }
        public string HCOName { get; set; }
        public int ApplicationTypeId { get; set; }
        public int AssessmentTypeId { get; set; }
        public int AssessorCapacityId { get; set; }
        public int HCOCityId { get; set; }
        public int StatusID { get; set; }
        public string PanNumber { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual ApplicationStatu ApplicationStatu { get; set; }
        public virtual ApplicationType ApplicationType { get; set; }
        public virtual AssessmentType AssessmentType { get; set; }
        public virtual City City { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssignmentDateDataForOtherPortal> AssignmentDateDataForOtherPortals { get; set; }
        public virtual ClaimTask ClaimTask { get; set; }
        public virtual ClaimTaskActivity ClaimTaskActivity { get; set; }
    }
}
