//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssessmentType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AssessmentType()
        {
            this.ApplicationTimeLines = new HashSet<ApplicationTimeLine>();
            this.ABPMJAYScoreSheetRights = new HashSet<ABPMJAYScoreSheetRight>();
            this.ApplicationStatusUpdatedByACMembers = new HashSet<ApplicationStatusUpdatedByACMember>();
            this.DeficienciesReports = new HashSet<DeficienciesReport>();
            this.PreAssessmentReportValues = new HashSet<PreAssessmentReportValue>();
            this.ReviewRemarks = new HashSet<ReviewRemark>();
            this.AssessorBloodBankNCs = new HashSet<AssessorBloodBankNC>();
            this.AssessorNonComplianceObservations = new HashSet<AssessorNonComplianceObservation>();
            this.FeedbackValues = new HashSet<FeedbackValue>();
            this.InCs = new HashSet<InC>();
            this.ManayataScoreSheetRights = new HashSet<ManayataScoreSheetRight>();
            this.mapAssessmentTypeNames = new HashSet<mapAssessmentTypeName>();
            this.ReviewUpdates = new HashSet<ReviewUpdate>();
            this.AssessorAssignments = new HashSet<AssessorAssignment>();
            this.AssessmentDataForOtherPortals = new HashSet<AssessmentDataForOtherPortal>();
        }
    
        public int AssessmentTypeID { get; set; }
        public string AssessmentType1 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicationTimeLine> ApplicationTimeLines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ABPMJAYScoreSheetRight> ABPMJAYScoreSheetRights { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicationStatusUpdatedByACMember> ApplicationStatusUpdatedByACMembers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeficienciesReport> DeficienciesReports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PreAssessmentReportValue> PreAssessmentReportValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReviewRemark> ReviewRemarks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssessorBloodBankNC> AssessorBloodBankNCs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssessorNonComplianceObservation> AssessorNonComplianceObservations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FeedbackValue> FeedbackValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InC> InCs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManayataScoreSheetRight> ManayataScoreSheetRights { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mapAssessmentTypeName> mapAssessmentTypeNames { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReviewUpdate> ReviewUpdates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssessorAssignment> AssessorAssignments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssessmentDataForOtherPortal> AssessmentDataForOtherPortals { get; set; }
    }
}
