//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssessorCertificate
    {
        public int CertificateID { get; set; }
        public int AssessorID { get; set; }
        public string CertificateNumber { get; set; }
        public bool IsVerified { get; set; }
        public int CategoryID { get; set; }
        public string AssessorCode { get; set; }
    
        public virtual AssessorCategory AssessorCategory { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
