//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssessorAssignment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AssessorAssignment()
        {
            this.assesmentSchedules = new HashSet<assesmentSchedule>();
            this.AssessmentSummaries = new HashSet<AssessmentSummary>();
            this.AssessorNonCompliances = new HashSet<AssessorNonCompliance>();
            this.AssessorObservations = new HashSet<AssessorObservation>();
            this.AssessorAssignmentDates = new HashSet<AssessorAssignmentDate>();
            this.DocumentAttachments = new HashSet<DocumentAttachment>();
            this.UploadDocuments = new HashSet<UploadDocument>();
        }
    
        public int AssignmentID { get; set; }
        public int AssessorID { get; set; }
        public int ApplicationID { get; set; }
        public int AssessorCapacityID { get; set; }
        public int AssessmentTypeID { get; set; }
        public bool IsFinalTeam { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual ApplicationStatu ApplicationStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<assesmentSchedule> assesmentSchedules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssessmentSummary> AssessmentSummaries { get; set; }
        public virtual AssessmentType AssessmentType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssessorNonCompliance> AssessorNonCompliances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssessorObservation> AssessorObservations { get; set; }
        public virtual tblUser tblUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssessorAssignmentDate> AssessorAssignmentDates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentAttachment> DocumentAttachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UploadDocument> UploadDocuments { get; set; }
        public virtual AssessorCapacity AssessorCapacity { get; set; }
    }
}
