//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssessorClaimLogin
    {
        public int id { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string emailId { get; set; }
        public string phoneNumber { get; set; }
        public string password { get; set; }
        public string Address { get; set; }
        public string AssessorId { get; set; }
        public string assessorAccountName { get; set; }
        public string bankName { get; set; }
        public string bankBranch { get; set; }
        public string bankIfsc { get; set; }
        public string bankAccountNo { get; set; }
        public string panNo { get; set; }
        public Nullable<int> accountType { get; set; }
        public Nullable<bool> IsVerified { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string fileNameCancelledCheck { get; set; }
        public string filePathCancelledCheck { get; set; }
        public string fileNamePanCard { get; set; }
        public string filePathPanCard { get; set; }
        public Nullable<int> CityId { get; set; }
        public string PinCode { get; set; }
        public string vendorFileName { get; set; }
        public string vendorFilePath { get; set; }
        public Nullable<bool> HasGSTIN { get; set; }
        public string GSTRegistrationNo { get; set; }
        public string gstFileName { get; set; }
        public string gstFilePath { get; set; }
        public string VendorId { get; set; }
    }
}
