//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ayurveda_OthersTreatment
    {
        public int ID { get; set; }
        public Nullable<int> AppID { get; set; }
        public string OtherTreatment { get; set; }
        public string Availability { get; set; }
        public string IPDBeds { get; set; }
    }
}
