//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class BloodBankApplication
    {
        public int ID { get; set; }
        public Nullable<int> ApplicationID { get; set; }
        public string Name { get; set; }
        public string Street { get; set; }
        public string Locality { get; set; }
        public string City { get; set; }
        public string District { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string Pincode { get; set; }
        public string website { get; set; }
        public string LicenseNumber { get; set; }
        public Nullable<System.DateTime> LicenseValidity { get; set; }
        public string NameOfPatentOrg { get; set; }
        public string PatentOrgPhone { get; set; }
        public string PatentOrgFax { get; set; }
        public string PatentOrgEmail { get; set; }
        public string LegalStatus { get; set; }
        public Nullable<System.DateTime> DateOfEstablishment { get; set; }
        public string Size { get; set; }
        public string OtherAccreditation { get; set; }
        public string ProficiencyProgrammes { get; set; }
        public Nullable<System.DateTime> InternalAuditDate { get; set; }
        public Nullable<System.DateTime> ReviewDate { get; set; }
        public Nullable<System.DateTime> ApplicationCompletionDate { get; set; }
        public Nullable<bool> TermAndCond { get; set; }
    
        public virtual Application Application { get; set; }
    }
}
