//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class BoardMeeting
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> MeetingDate { get; set; }
        public string MeetingTime { get; set; }
        public string Agenda { get; set; }
        public string AgendaDetails { get; set; }
        public string Venue { get; set; }
        public string Decision { get; set; }
        public Nullable<int> DecisionTakenBy { get; set; }
        public Nullable<int> AgendaCreatedBy { get; set; }
        public Nullable<System.DateTime> DecisionDate { get; set; }
        public string AttendanceDocument { get; set; }
        public string MOMDocument { get; set; }
    }
}
