//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHCService
    {
        public int ID { get; set; }
        public int ApplicationID { get; set; }
        public Nullable<bool> OPDAvailable { get; set; }
        public string OPDRemarks { get; set; }
        public Nullable<bool> EmergencyAvailable { get; set; }
        public string EmergencyRemarks { get; set; }
        public Nullable<bool> ReferalAvailable { get; set; }
        public string ReferalRemarks { get; set; }
        public Nullable<bool> InPatientAvailable { get; set; }
        public string InPatientRemarks { get; set; }
        public Nullable<int> NumberOfBedsAvailable { get; set; }
        public string BedOccupancy { get; set; }
        public string BedAvailableRemarks { get; set; }
        public string BedOccupancyRemarks { get; set; }
        public Nullable<int> NumberOfInpatientBed { get; set; }
        public string NumberOfInpatentBedRemarks { get; set; }
        public Nullable<bool> LabourRoom { get; set; }
        public string LabourRoomRemarks { get; set; }
        public Nullable<bool> OperationTheatre { get; set; }
        public string OperationTheatreRemarks { get; set; }
        public Nullable<bool> Genrator { get; set; }
        public string GenratorRemarks { get; set; }
        public Nullable<bool> ColdChain { get; set; }
        public string ColdChainRemarks { get; set; }
        public Nullable<bool> Licence { get; set; }
        public string LicenceRemarks { get; set; }
    
        public virtual Application Application { get; set; }
    }
}
