//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class CIGeneralInfo
    {
        public int ID { get; set; }
        public Nullable<int> ApplicationID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string HospitalName { get; set; }
        public Nullable<int> ICUBeds { get; set; }
        public Nullable<int> NonICUBeds { get; set; }
        public Nullable<int> Doctors { get; set; }
        public Nullable<int> Nurses { get; set; }
        public Nullable<int> OTTables { get; set; }
        public Nullable<int> AvgAdmissions { get; set; }
        public Nullable<int> AvgOPD { get; set; }
        public Nullable<int> AvgEmergency { get; set; }
        public Nullable<int> AvgElectiveSurgries { get; set; }
        public Nullable<int> AvgEmergencySurgeries { get; set; }
        public Nullable<int> AvgDayCareSurgries { get; set; }
        public string AvgWaterConsumed { get; set; }
        public string AvgElectricityConsumed { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> TotalBeds { get; set; }
        public Nullable<bool> SaveEdit { get; set; }
    }
}
