//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class CIMasterIndicatorName
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string IndicatorName { get; set; }
        public string DataDesc1 { get; set; }
        public string DataDesc2 { get; set; }
        public string Tracability1 { get; set; }
        public string Tracability2 { get; set; }
        public string Formula { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> applicationtypeid { get; set; }
        public Nullable<bool> Active { get; set; }
        public string Unit { get; set; }
        public string Fdata { get; set; }
    }
}
