//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class circular
    {
        public int id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string circularno { get; set; }
        public string subject { get; set; }
        public string filename { get; set; }
        public string filepath { get; set; }
        public string description { get; set; }
        public string name { get; set; }
        public string designation { get; set; }
        public string viewnotview { get; set; }
    }
}
