//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClaimTaskActivity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClaimTaskActivity()
        {
            this.mapClaimFees = new HashSet<mapClaimFee>();
            this.AssessmentDataForOtherPortals = new HashSet<AssessmentDataForOtherPortal>();
        }
    
        public int id { get; set; }
        public int TaskId { get; set; }
        public string name { get; set; }
        public Nullable<decimal> DAfees { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mapClaimFee> mapClaimFees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssessmentDataForOtherPortal> AssessmentDataForOtherPortals { get; set; }
    }
}
