//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClinicalServiceType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClinicalServiceType()
        {
            this.ClinicalServiceValues = new HashSet<ClinicalServiceValue>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string GroupTitle { get; set; }
        public int ApplicationType { get; set; }
        public bool Others { get; set; }
    
        public virtual ApplicationType ApplicationType1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClinicalServiceValue> ClinicalServiceValues { get; set; }
    }
}
