//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClinicalTrialGeneralInfo
    {
        public int ID { get; set; }
        public int ApplicationID { get; set; }
        public string AccreditationType { get; set; }
        public Nullable<System.DateTime> ValidFrom { get; set; }
        public Nullable<System.DateTime> VaidTo { get; set; }
        public string HospitalName { get; set; }
        public string OwnershipType { get; set; }
        public string RegDetails { get; set; }
        public string FunctionStarted { get; set; }
        public int TotalNoOfBeds { get; set; }
        public Nullable<System.DateTime> ApplicationCompletedDate { get; set; }
        public string Ownership { get; set; }
        public string Street { get; set; }
        public string Locality { get; set; }
        public string City { get; set; }
        public string District { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string Pincode { get; set; }
        public Nullable<bool> IsFirstTimeAcc { get; set; }
        public Nullable<bool> RenewAcc { get; set; }
        public Nullable<bool> TandCCheck { get; set; }
        public string Website { get; set; }
        public string OngoingCT { get; set; }
    }
}
