//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClosedTrainingDetail
    {
        public int ID { get; set; }
        public Nullable<int> EventID { get; set; }
        public string ProgramName { get; set; }
        public string frmdate { get; set; }
        public string toDate { get; set; }
        public string City { get; set; }
        public string Username { get; set; }
        public string EmailID { get; set; }
        public string MobileNo { get; set; }
        public string TransactionID { get; set; }
        public string TransactionDate { get; set; }
        public string CertNo { get; set; }
        public Nullable<bool> Attendance { get; set; }
        public Nullable<bool> Verified { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string FileName { get; set; }
        public string Schedule { get; set; }
    }
}
