//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Complaint
    {
        public int ID { get; set; }
        public string HCOName { get; set; }
        public Nullable<int> ComplainantID { get; set; }
        public string Subject { get; set; }
        public string Complaint1 { get; set; }
        public bool Forwarded { get; set; }
        public bool Dismissed { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ComplainantEmail { get; set; }
        public string ComplainantPhone { get; set; }
        public string ComplainantName { get; set; }
        public string HCOcity { get; set; }
        public string HCOState { get; set; }
        public string HCOaddress { get; set; }
    }
}
