//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTDecForm
    {
        public int ID { get; set; }
        public int ApplicationID { get; set; }
        public Nullable<int> CTSiteID { get; set; }
        public string FacilitiesAvailable { get; set; }
        public string HsopitalName { get; set; }
        public string Address { get; set; }
        public string Accessibility { get; set; }
        public string ExistingAccr { get; set; }
        public string RegisteredEC { get; set; }
        public Nullable<int> TotalNoOfProtocols { get; set; }
        public Nullable<int> TotalNoOfOngoingCT { get; set; }
        public Nullable<int> TotalNoofCtStaff { get; set; }
    }
}
