//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTDocumentAttachment
    {
        public int ID { get; set; }
        public int ApplicationID { get; set; }
        public int UserID { get; set; }
        public int RefDocID { get; set; }
        public string DocumentName { get; set; }
        public string PathAdd { get; set; }
    }
}
