//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeficienciesReport
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DeficienciesReport()
        {
            this.EvidenceAttachments = new HashSet<EvidenceAttachment>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ApplicationID { get; set; }
        public Nullable<int> AssessorID { get; set; }
        public Nullable<int> AssessmentTypeID { get; set; }
        public string Deficency { get; set; }
        public string Remarks { get; set; }
        public string CorrectiveAction { get; set; }
        public string AssessorRemarks { get; set; }
        public string Status { get; set; }
        public string saveedit { get; set; }
        public string ReferenceForObjectiveElements { get; set; }
        public Nullable<bool> Cycle { get; set; }
        public Nullable<System.DateTime> Createdon { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual AssessmentType AssessmentType { get; set; }
        public virtual tblUser tblUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EvidenceAttachment> EvidenceAttachments { get; set; }
    }
}
