//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Demo_CopyOfHCO
    {
        public int id { get; set; }
        public string address { get; set; }
        public string pincode { get; set; }
        public string certificate_no { get; set; }
        public string clinicalservice { get; set; }
    }
}
