//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class DentalOutDepartment
    {
        public int ID { get; set; }
        public int ApplicationID { get; set; }
        public string DeptName { get; set; }
        public Nullable<int> NumOfChairs { get; set; }
        public Nullable<int> AvgPatients { get; set; }
        public string Services { get; set; }
    
        public virtual Application Application { get; set; }
    }
}
