//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailsofManualValue
    {
        public int id { get; set; }
        public int DetailsofManualId { get; set; }
        public System.DateTime issueDate { get; set; }
        public string approvedBy { get; set; }
        public bool isManualRevised { get; set; }
        public System.DateTime lastRevisionDate { get; set; }
        public Nullable<bool> appointmentOfDesignatedPersonnel { get; set; }
        public string nameOfDesignatedPerson { get; set; }
        public System.DateTime editOn { get; set; }
        public string filename { get; set; }
        public string filepath { get; set; }
        public Nullable<int> applicationId { get; set; }
        public Nullable<int> saveEdit { get; set; }
        public Nullable<bool> isAccepted { get; set; }
        public string remarkByAssessor { get; set; }
    }
}
