//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiagnosticEquipValue
    {
        public int ID { get; set; }
        public int DepartmentID { get; set; }
        public int ApplicationID { get; set; }
        public Nullable<bool> InHouse { get; set; }
        public Nullable<bool> OutSourced { get; set; }
        public Nullable<int> Number { get; set; }
    
        public virtual Application Application { get; set; }
    }
}
