//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ECDeclarartionForm
    {
        public int ID { get; set; }
        public Nullable<int> ApplicationID { get; set; }
        public Nullable<int> EthicsCommitteeID { get; set; }
        public Nullable<System.DateTime> RegDate { get; set; }
        public Nullable<int> NoOfCTPropsals { get; set; }
        public Nullable<int> NoOfCTAnnually { get; set; }
        public Nullable<int> TotalNoOfProtocols { get; set; }
    
        public virtual EthicsCommitteeInfo EthicsCommitteeInfo { get; set; }
    }
}
