//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ECHSRecommendedList
    {
        public int ID { get; set; }
        public Nullable<int> ApplicantID { get; set; }
        public string RecommendationNumber { get; set; }
        public string Recommended { get; set; }
        public string NotRecommended { get; set; }
        public Nullable<System.DateTime> RecommendedDate { get; set; }
        public string FileName { get; set; }
        public string FileURL { get; set; }
        public Nullable<bool> IsBlock { get; set; }
        public Nullable<System.DateTime> lastUpdateDate { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual EchsApplicant EchsApplicant { get; set; }
    }
}
