//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class EchsApplicant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EchsApplicant()
        {
            this.EchsApplicantChangeLogs = new HashSet<EchsApplicantChangeLog>();
            this.ECHSRecommendedLists = new HashSet<ECHSRecommendedList>();
        }
    
        public int ID { get; set; }
        public string ApplicationNumber { get; set; }
        public string Name { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<System.DateTime> RecieveDate { get; set; }
        public string AppliedFor { get; set; }
        public string Type { get; set; }
        public Nullable<bool> IsBlock { get; set; }
        public Nullable<System.DateTime> lastUpdateDate { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EchsApplicantChangeLog> EchsApplicantChangeLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ECHSRecommendedList> ECHSRecommendedLists { get; set; }
    }
}
