//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmergencyData
    {
        public int ID { get; set; }
        public int ApplicationID { get; set; }
        public string Type { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> NumOfPatient { get; set; }
    }
}
