//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmergencyStaffValue
    {
        public int ID { get; set; }
        public int StaffInfoID { get; set; }
        public int ApplicationID { get; set; }
        public Nullable<int> Number { get; set; }
        public Nullable<bool> Inhouse { get; set; }
        public Nullable<bool> Oncall { get; set; }
    }
}
