//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipments2
    {
        public int ID { get; set; }
        public int ApplicationID { get; set; }
        public string Name { get; set; }
        public string RegistrationNumber { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public Nullable<System.DateTime> ValidUpto { get; set; }
        public string Remarks { get; set; }
    
        public virtual Application Application { get; set; }
    }
}
