//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventAddress
    {
        public int ID { get; set; }
        public Nullable<int> EventID { get; set; }
        public string Addres { get; set; }
        public string city { get; set; }
        public string Region { get; set; }
        public string State { get; set; }
        public Nullable<int> PostalCode { get; set; }
        public string Country { get; set; }
    
        public virtual NabhEvent NabhEvent { get; set; }
    }
}
