//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class eventpaymentDetailRemark
    {
        public int Id { get; set; }
        public string Remark { get; set; }
        public int EventOrderId { get; set; }
        public System.DateTime CreateOn { get; set; }
    
        public virtual NabhEventOrder NabhEventOrder { get; set; }
    }
}
