//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class EyeOtherBedInformation
    {
        public int ID { get; set; }
        public Nullable<int> ApplicationID { get; set; }
        public Nullable<int> SanctionedBeds { get; set; }
        public Nullable<int> CurrentlyInOperationBeds { get; set; }
        public Nullable<int> InPatientBeds { get; set; }
        public Nullable<int> OTNumber { get; set; }
        public Nullable<int> NumberOfBuilding { get; set; }
        public Nullable<int> Surgeries { get; set; }
        public string BedOccupancy { get; set; }
        public Nullable<int> DayCareBeds { get; set; }
        public Nullable<int> TotalBeds { get; set; }
    }
}
