//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeedbackValue
    {
        public int ID { get; set; }
        public Nullable<int> FeedbackID { get; set; }
        public Nullable<int> ApplicationID { get; set; }
        public Nullable<int> AssessorID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> AssessmentTypeID { get; set; }
        public Nullable<bool> Provided { get; set; }
        public string Remarks { get; set; }
        public string DropDownValue { get; set; }
    
        public virtual AssessmentType AssessmentType { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
