//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class getAllPaymentDetail
    {
        public int hdnAppID { get; set; }
        public Nullable<System.DateTime> fromdate { get; set; }
        public Nullable<System.DateTime> todate { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string date { get; set; }
        public string PaymentMode { get; set; }
        public string DDNumber { get; set; }
        public string UTRNumber { get; set; }
        public string TransactionID { get; set; }
        public string status { get; set; }
        public string AttachmentPath { get; set; }
        public string TANNo { get; set; }
        public string PANNo { get; set; }
        public string GSTNo { get; set; }
        public string AttachmentName { get; set; }
        public string filename { get; set; }
        public string filpath { get; set; }
        public string filename2 { get; set; }
        public string filpath2 { get; set; }
        public int pid { get; set; }
        public string PaymentType { get; set; }
        public Nullable<int> ApplicationID { get; set; }
        public string Number { get; set; }
        public string Type { get; set; }
        public string Code { get; set; }
        public string ApplicationType { get; set; }
    }
}
