//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class HCOApplicantList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HCOApplicantList()
        {
            this.HCOAccreditedLists = new HashSet<HCOAccreditedList>();
            this.otherHCODetails = new HashSet<otherHCODetail>();
            this.HCOApplicantChangeLogs = new HashSet<HCOApplicantChangeLog>();
            this.HCOProgressiveLists = new HashSet<HCOProgressiveList>();
        }
    
        public int ID { get; set; }
        public string ReferenceNumber { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> DateOfReceived { get; set; }
        public string PresentStatus { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> ApplicationTypeID { get; set; }
        public Nullable<bool> IsBlock { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HCOAccreditedList> HCOAccreditedLists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<otherHCODetail> otherHCODetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HCOApplicantChangeLog> HCOApplicantChangeLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HCOProgressiveList> HCOProgressiveLists { get; set; }
    }
}
