//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class HCOAccreditedList
    {
        public int ID { get; set; }
        public Nullable<int> ApplicantID { get; set; }
        public string AccreditationNumber { get; set; }
        public Nullable<System.DateTime> DateFrom { get; set; }
        public Nullable<System.DateTime> DateTo { get; set; }
        public string Website { get; set; }
        public string FileName { get; set; }
        public string FileUrl { get; set; }
        public Nullable<bool> IsBlock { get; set; }
        public string Remark { get; set; }
    
        public virtual HCOApplicantList HCOApplicantList { get; set; }
    }
}
