//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class HCOBulkPaymentDetail
    {
        public int Id { get; set; }
        public string UTRNumber { get; set; }
        public int UseLimit { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public string fileName { get; set; }
        public string filePath { get; set; }
    
        public virtual tblUser tblUser { get; set; }
    }
}
