//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class HospitalOthersBedInformation
    {
        public int ID { get; set; }
        public Nullable<int> ApplicationID { get; set; }
        public Nullable<int> SectionedBeds { get; set; }
        public Nullable<int> CurrentlyInOperationBeds { get; set; }
        public Nullable<int> InPatientBedsNonICU { get; set; }
        public Nullable<int> InPatientBedsICU { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<int> Speciality { get; set; }
        public Nullable<int> SuperSpeciality { get; set; }
        public Nullable<int> NumberOfBuildings { get; set; }
        public string BedOccupancy { get; set; }
        public Nullable<int> EmergencyBeds { get; set; }
        public Nullable<int> Daycarebeds { get; set; }
        public Nullable<int> RecoveryRoomBeds { get; set; }
        public Nullable<int> LabourRoomBeds { get; set; }
        public Nullable<int> Dialysis { get; set; }
        public Nullable<int> SingleOccupancyBeds { get; set; }
        public Nullable<int> DoubleOccupancyBeds { get; set; }
        public Nullable<int> Dormitory { get; set; }
        public Nullable<int> Cubicles { get; set; }
        public Nullable<int> BedOccupancyInYear { get; set; }
    
        public virtual Application Application { get; set; }
    }
}
