//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class IEvent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IEvent()
        {
            this.IDocuments = new HashSet<IDocument>();
        }
    
        public int ID { get; set; }
        public int TypeID { get; set; }
        public int StatusID { get; set; }
        public int OrganizationID { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string TransactionID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IDocument> IDocuments { get; set; }
        public virtual IEventStatu IEventStatu { get; set; }
        public virtual IEventType IEventType { get; set; }
        public virtual IOrganization IOrganization { get; set; }
    }
}
