//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class InC
    {
        public int InCDocumentID { get; set; }
        public int AssessorID { get; set; }
        public int ApplicationID { get; set; }
        public Nullable<int> SecMemID { get; set; }
        public Nullable<System.DateTime> DateOfAssessment { get; set; }
        public Nullable<int> TypeOfAssessment { get; set; }
        public Nullable<int> AssessorCapacity { get; set; }
        public Nullable<bool> AssessorAgreed { get; set; }
        public Nullable<bool> SecAgreed { get; set; }
        public Nullable<int> SecCapacity { get; set; }
    
        public virtual AssessmentType AssessmentType { get; set; }
        public virtual AssessorCapacity AssessorCapacity1 { get; set; }
        public virtual SecretariatMemberCapacity SecretariatMemberCapacity { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
