//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndividualEducationExperience
    {
        public int ExperienceID { get; set; }
        public Nullable<int> ApplicationID { get; set; }
        public string EducationalQualification { get; set; }
        public string SpecializedDegree { get; set; }
        public Nullable<int> TotalWorkExperience { get; set; }
        public Nullable<int> NABHImplementationExperience { get; set; }
        public Nullable<bool> NABHPOIattended { get; set; }
        public string NABHPOIStandards { get; set; }
        public Nullable<bool> AccreditationSupportProjects { get; set; }
        public Nullable<bool> CertifiedSupportProjects { get; set; }
        public Nullable<bool> CurrentNABHAssessor { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<int> CertifiedOrganizationsCount { get; set; }
        public Nullable<int> AccreditedOrganizationsCount { get; set; }
        public Nullable<int> HospitalITExperience { get; set; }
        public Nullable<int> HisEmrExperience { get; set; }
        public Nullable<int> ItInfrastructureExperience { get; set; }
        public Nullable<int> AdvisoryExperience { get; set; }
    
        public virtual MitraApplication MitraApplication { get; set; }
    }
}
