//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfectionControlClinicChecklistValue
    {
        public int id { get; set; }
        public string filename { get; set; }
        public string filePath { get; set; }
        public string remark { get; set; }
        public bool isAccepted { get; set; }
        public string remarkByAssessor { get; set; }
        public int applicationId { get; set; }
        public string Speciality { get; set; }
        public Nullable<int> saveEdit { get; set; }
    }
}
