//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfectionControlEquipmentChecklistValue
    {
        public int id { get; set; }
        public Nullable<int> InfectionControlEquipmentChecklistId { get; set; }
        public Nullable<bool> Autoclaving { get; set; }
        public Nullable<bool> glassBeadSterilizer { get; set; }
        public Nullable<bool> UVChamber { get; set; }
        public Nullable<bool> surfacedisinfectant { get; set; }
        public Nullable<bool> laundry { get; set; }
        public Nullable<bool> disposable { get; set; }
        public Nullable<bool> washing { get; set; }
    }
}
