//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class insert_shco_listambulatory
    {
        public int id { get; set; }
        public Nullable<int> serviceid { get; set; }
        public string applicationid { get; set; }
        public string Name { get; set; }
        public string noofbeds { get; set; }
        public string typeofcare { get; set; }
    }
}
