//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class insertshcostaffinfo
    {
        public int id { get; set; }
        public Nullable<int> serviceid { get; set; }
        public string appid { get; set; }
        public string totalnumber { get; set; }
        public string remark { get; set; }
        public string sgroup { get; set; }
    }
}
