//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvestigatorDecForm
    {
        public int ID { get; set; }
        public Nullable<int> ApplicationID { get; set; }
        public Nullable<int> InvestigatorID { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string RegNum { get; set; }
        public string Degree { get; set; }
        public Nullable<int> ExpCP { get; set; }
        public Nullable<int> ExpCT { get; set; }
        public Nullable<int> TotalNoInvestigators { get; set; }
        public Nullable<int> TotalNoOfSubInvestigators { get; set; }
        public Nullable<int> CurrentNoOftrials { get; set; }
        public string CorresAddress { get; set; }
        public string PermAddress { get; set; }
        public string CTName { get; set; }
        public string AccConfirmation { get; set; }
        public string NABHAccCertNo { get; set; }
    }
}
