//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class IRCA_CheckPointsValues
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IRCA_CheckPointsValues()
        {
            this.IRCA_CheckPointsFileUpload = new HashSet<IRCA_CheckPointsFileUpload>();
            this.IRCA_CheckPointsFileUpload2 = new HashSet<IRCA_CheckPointsFileUpload2>();
        }
    
        public int Id { get; set; }
        public string IndicatorId { get; set; }
        public int ApplicationId { get; set; }
        public string GradeAchieved { get; set; }
        public Nullable<int> Scoresobtained { get; set; }
        public string Remark { get; set; }
        public Nullable<int> SaveEdit { get; set; }
        public string CheckPointType { get; set; }
        public Nullable<int> InPlaceStaff { get; set; }
        public Nullable<int> AssessmentTypeID { get; set; }
        public Nullable<int> AssessorID { get; set; }
        public string CentreRemark { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        public virtual Application Application { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IRCA_CheckPointsFileUpload> IRCA_CheckPointsFileUpload { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IRCA_CheckPointsFileUpload2> IRCA_CheckPointsFileUpload2 { get; set; }
    }
}
