//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class IRCA_CheckPoints2
    {
        public int Id { get; set; }
        public string Indicator { get; set; }
        public string Description { get; set; }
        public string MeansofVerification { get; set; }
        public string Grading { get; set; }
        public Nullable<decimal> IndicatorId { get; set; }
        public Nullable<bool> isMandatory { get; set; }
        public string CheckPointType { get; set; }
        public string Heading { get; set; }
    }
}
