//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Journal
    {
        public int ID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }
        public string Keywords { get; set; }
        public string PublicationMonth { get; set; }
        public string PublicationYear { get; set; }
        public string ISSN { get; set; }
        public string VolumeNumber { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string CoverImage { get; set; }
        public string NoOfImages { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<bool> IsPublished { get; set; }
    }
}
