//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class LaboratoryTest
    {
        public int ID { get; set; }
        public int ApplicationID { get; set; }
        public string LaboratoryDiscipline { get; set; }
        public string TestName { get; set; }
        public string MethodOfTesting { get; set; }
        public Nullable<int> AvgDailyTestCount { get; set; }
        public string InternalQualityControl { get; set; }
        public Nullable<bool> Others { get; set; }
    
        public virtual Application Application { get; set; }
    }
}
