//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class LaboratoryEquipment
    {
        public int ID { get; set; }
        public int ApplicationID { get; set; }
        public string ListofLaboratoryEquipment { get; set; }
        public string EquipmentID { get; set; }
        public Nullable<System.DateTime> DateOfInstallation { get; set; }
        public string ModelNumber { get; set; }
        public string ManufacturersName { get; set; }
        public Nullable<System.DateTime> LastDateOfCalibration { get; set; }
        public Nullable<System.DateTime> DueDateOfCalibration { get; set; }
        public string PresentWorkingStatus { get; set; }
    
        public virtual Application Application { get; set; }
    }
}
