//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class LicenseValue
    {
        public int ID { get; set; }
        public int LicenseTypeID { get; set; }
        public int ApplicationID { get; set; }
        public string LicenseNumber { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> ValidUpto { get; set; }
        public string Remarks { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> renewalDate { get; set; }
        public string isSelected { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual LicenseType LicenseType { get; set; }
    }
}
