//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginLog
    {
        public int L_Id { get; set; }
        public string L_Email { get; set; }
        public string L_UserIP { get; set; }
        public string L_ECIP { get; set; }
        public Nullable<System.DateTime> L_LoginDateTime { get; set; }
        public Nullable<int> L_Good_Password { get; set; }
    }
}
