//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class mapClaimFee
    {
        public int Id { get; set; }
        public int AccreditationCertificationProgrammeId { get; set; }
        public int ProgramId { get; set; }
        public int ActivityTypeId { get; set; }
        public decimal PrincipalAssessorFees { get; set; }
        public decimal COAssssorFees { get; set; }
        public decimal PerDayFees { get; set; }
        public decimal UpTo4hrfees { get; set; }
        public Nullable<decimal> DAfees { get; set; }
        public Nullable<decimal> reviewFees { get; set; }
        public Nullable<decimal> FixedMiscellaneous { get; set; }
    
        public virtual ClaimProgramme ClaimProgramme { get; set; }
        public virtual ClaimTask ClaimTask { get; set; }
        public virtual ClaimTaskActivity ClaimTaskActivity { get; set; }
    }
}
