//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class MISApplication
    {
        public int ID { get; set; }
        public int ApplicationID { get; set; }
        public string Name { get; set; }
        public string Street { get; set; }
        public string Locality { get; set; }
        public string City { get; set; }
        public string District { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string Pincode { get; set; }
        public string Website { get; set; }
        public string Ownership { get; set; }
        public string ParentOrganization { get; set; }
        public string ParentPhone { get; set; }
        public string ParentFax { get; set; }
        public string ParentEmail { get; set; }
        public string CertificateName { get; set; }
        public string Registered { get; set; }
        public Nullable<System.DateTime> SelfAssessmentDoneOn { get; set; }
        public string DoneBy { get; set; }
        public Nullable<System.DateTime> ApplicationCompletedOn { get; set; }
        public string Litigation { get; set; }
        public Nullable<bool> TermAndCond { get; set; }
    
        public virtual Application Application { get; set; }
    }
}
