//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class misRegistrationDocument
    {
        public int id { get; set; }
        public string applicationid { get; set; }
        public string userid { get; set; }
        public Nullable<int> satid { get; set; }
        public string reference { get; set; }
        public string pathadd { get; set; }
    }
}
