//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class MitraIndvInfrastructure
    {
        public int Id { get; set; }
        public int ApplicationId { get; set; }
        public Nullable<bool> DedicatedWorkspace { get; set; }
        public Nullable<bool> LaptopDesktop { get; set; }
        public Nullable<bool> VirtualMeetingTools { get; set; }
        public Nullable<bool> OnsiteVisit { get; set; }
        public Nullable<bool> TrainingTools { get; set; }
        public Nullable<bool> DigitalProficiency { get; set; }
        public Nullable<bool> ITSupport { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    
        public virtual MitraApplication MitraApplication { get; set; }
    }
}
