//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class MitraApplication
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MitraApplication()
        {
            this.IndividualEducationExperiences = new HashSet<IndividualEducationExperience>();
            this.MitraHCOsupporteds = new HashSet<MitraHCOsupported>();
            this.MitraIndvInfrastructures = new HashSet<MitraIndvInfrastructure>();
            this.MitraEnclosures = new HashSet<MitraEnclosure>();
            this.MitraOrgInfrastructures = new HashSet<MitraOrgInfrastructure>();
            this.Professionals = new HashSet<Professional>();
            this.tblReferences = new HashSet<tblReference>();
        }
    
        public int Id { get; set; }
        public string Category { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string OrganizationName { get; set; }
        public string OrganizationHeadName { get; set; }
        public string TypeOfLegalEntity { get; set; }
        public string OtherLegalEntity { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public Nullable<int> PermanentEmployees { get; set; }
        public Nullable<int> ContractualEmployees { get; set; }
        public string ResidentialAddress { get; set; }
        public string ResidentialDistrict { get; set; }
        public string ResidentialCity { get; set; }
        public string ResidentialState { get; set; }
        public string ResidentialPinCode { get; set; }
        public string CommunicationAddress { get; set; }
        public string CommunicationDistrict { get; set; }
        public string CommunicationCity { get; set; }
        public string CommunicationState { get; set; }
        public string CommunicationPinCode { get; set; }
        public string Phone { get; set; }
        public string EmailID { get; set; }
        public string AlternateEmailID { get; set; }
        public string Website { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string GovtIDNumber { get; set; }
        public string PANNumber { get; set; }
        public string TANNumber { get; set; }
        public Nullable<bool> AccreditationSupportProjects { get; set; }
        public Nullable<int> AccreditedOrganizationsCount { get; set; }
        public Nullable<bool> CertificationSupportProjects { get; set; }
        public Nullable<int> CertifiedOrganizationsCount { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<bool> IsInfoCorrect { get; set; }
        public Nullable<bool> IsAgreeToAbide { get; set; }
        public string OrgHeadName { get; set; }
        public string ApplicantName { get; set; }
        public string Place { get; set; }
        public string GovtIdType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IndividualEducationExperience> IndividualEducationExperiences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MitraHCOsupported> MitraHCOsupporteds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MitraIndvInfrastructure> MitraIndvInfrastructures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MitraEnclosure> MitraEnclosures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MitraOrgInfrastructure> MitraOrgInfrastructures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Professional> Professionals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblReference> tblReferences { get; set; }
    }
}
