//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class MitraHCOsupported
    {
        public int HCOExperienceID { get; set; }
        public Nullable<int> ApplicationID { get; set; }
        public string HCOName { get; set; }
        public Nullable<int> SanctionedBeds { get; set; }
        public string AccreditationType { get; set; }
        public Nullable<System.DateTime> PeriodOfSupportFrom { get; set; }
        public Nullable<System.DateTime> PeriodOfSupportTo { get; set; }
        public string ServicesProvided { get; set; }
        public string ContactPersonName { get; set; }
        public string ContactPersonDesignation { get; set; }
        public string ContactDetails { get; set; }
        public string emailId { get; set; }
        public string phone { get; set; }
        public string Outcome { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string fileName { get; set; }
        public string filePath { get; set; }
        public string HCORefNo { get; set; }
    
        public virtual MitraApplication MitraApplication { get; set; }
    }
}
