//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class MitraEnclosure
    {
        public int Id { get; set; }
        public int ApplicationId { get; set; }
        public string ApplicationType { get; set; }
        public string DocType { get; set; }
        public string FileName { get; set; }
        public string FilePath { get; set; }
        public Nullable<System.DateTime> UploadedAt { get; set; }
    
        public virtual MitraApplication MitraApplication { get; set; }
    }
}
