//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class MITRA_Empanelment_Applications
    {
        public int ApplicationID { get; set; }
        public string ApplicationCategory { get; set; }
        public string ApplicantName { get; set; }
        public string LegalEntityType { get; set; }
        public string OtherLegalEntityType { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public string AuthorizedRepresentativeName { get; set; }
        public string RegisteredAddressLine1 { get; set; }
        public string RegisteredAddressLine2 { get; set; }
        public string PinCode { get; set; }
        public string State { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public string Website { get; set; }
        public Nullable<int> PermanentEmployees { get; set; }
        public Nullable<int> ContractualEmployees { get; set; }
        public string PANNumber { get; set; }
        public string GSTNumber { get; set; }
        public Nullable<System.DateTime> OperationalStartDate { get; set; }
        public Nullable<int> TotalExperienceYears { get; set; }
        public Nullable<int> NABHProjectsSupported { get; set; }
        public string EducationalQualification { get; set; }
        public string SpecializedDegree { get; set; }
        public string NABHPOI_TrainingCertificateNumber { get; set; }
        public Nullable<System.DateTime> NABHPOI_TrainingCertificateDate { get; set; }
        public Nullable<int> IndividualProfessionalExperienceYears { get; set; }
        public Nullable<int> IndividualNABHExperienceYears { get; set; }
        public Nullable<int> QualifiedProfessionalsCount { get; set; }
        public Nullable<int> InHouseMedicalExpertsCount { get; set; }
        public Nullable<int> NABHCertifiedMITRAsCount { get; set; }
        public Nullable<bool> HasDedicatedOfficeSpace { get; set; }
        public Nullable<bool> HasMeetingRoom { get; set; }
        public Nullable<bool> HasTrainingAids { get; set; }
        public Nullable<bool> HasITSetup { get; set; }
        public Nullable<bool> HasLibrary { get; set; }
        public Nullable<bool> HasDedicatedHomeWorkspace { get; set; }
        public Nullable<bool> HasLaptopDesktop { get; set; }
        public Nullable<bool> HasVirtualMeetingTools { get; set; }
        public Nullable<bool> HasProjectorTrainingTools { get; set; }
        public Nullable<bool> CanVisitHospitalsOnSite { get; set; }
        public Nullable<bool> PANCardAttached { get; set; }
        public Nullable<bool> GSTCertificateAttached { get; set; }
        public Nullable<bool> EducationCertsAttached { get; set; }
        public Nullable<bool> NABHPOICertAttached { get; set; }
        public Nullable<bool> HCOsSupportedListAttached { get; set; }
        public Nullable<bool> StaffProfilesAttached { get; set; }
        public Nullable<bool> InfrastructurePhotosAttached { get; set; }
        public string OtherEnclosures { get; set; }
        public bool Declaration_CorrectInfo { get; set; }
        public bool Declaration_AbideByTerms { get; set; }
        public string PANCard { get; set; }
        public string GSTCertificate { get; set; }
        public string EducationCerts { get; set; }
        public string NABHPOICert { get; set; }
        public string HCOsSupportedList { get; set; }
        public string StaffProfiles { get; set; }
        public string InfrastructurePhotos { get; set; }
        public string officeAddress { get; set; }
        public string officepinCode { get; set; }
        public string officestate { get; set; }
        public string region { get; set; }
        public string email2 { get; set; }
        public string designation { get; set; }
        public Nullable<int> organizationExp { get; set; }
        public string govtIdNumber { get; set; }
        public string currentOrganizationManagement { get; set; }
        public string poiAttended { get; set; }
        public string poiStandard { get; set; }
        public string IsNabhAssessor { get; set; }
        public string AccOrCertProjectSupported { get; set; }
        public Nullable<int> noEmpPoiAttended { get; set; }
        public Nullable<System.DateTime> DateNabhTraininAttended { get; set; }
        public Nullable<bool> PhotographAttached { get; set; }
        public string PhotographPath { get; set; }
        public Nullable<bool> SighAttached { get; set; }
        public string SighPath { get; set; }
        public string fName { get; set; }
        public string mName { get; set; }
        public string lName { get; set; }
        public string City1 { get; set; }
        public string City2 { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<bool> IsAccreditationSupported { get; set; }
        public Nullable<int> AccreditationSupportedExp { get; set; }
        public Nullable<bool> IsCertificationSupported { get; set; }
        public Nullable<int> CertificationSupportedExp { get; set; }
        public Nullable<int> VisitingProfessionalCount { get; set; }
        public Nullable<int> InHouseProfessionalCount { get; set; }
        public Nullable<bool> HasOnSiteVisitCapability { get; set; }
        public string Ref1Name { get; set; }
        public string Ref1Designation { get; set; }
        public string Ref1Organisation { get; set; }
        public string Ref1Email { get; set; }
        public string Ref1Phone { get; set; }
        public string Ref2Name { get; set; }
        public string Ref2Designation { get; set; }
        public string Ref2Organisation { get; set; }
        public string Ref2Email { get; set; }
        public string Ref2Phone { get; set; }
        public Nullable<bool> ListofProfessionalAttached { get; set; }
        public string ListofProfessionalPath { get; set; }
        public Nullable<bool> ExperienceListinHCOsAttached { get; set; }
        public string ExperienceListinHCOs { get; set; }
        public Nullable<bool> ListofEmployeesattendedPOIAttached { get; set; }
        public string ListofEmployeesattendedPOIPath { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    }
}
