//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class MLPApplication
    {
        public int ID { get; set; }
        public int ApplicationID { get; set; }
        public string Name { get; set; }
        public string ParentOrgName { get; set; }
        public string ParentOrgTel { get; set; }
        public string ParentOrgFax { get; set; }
        public string ParentOrgEmail { get; set; }
        public string LegalStatus { get; set; }
        public Nullable<System.DateTime> YearOfEstablishment { get; set; }
        public string AvgDailyPatientLoad { get; set; }
        public string OtherCertification { get; set; }
        public Nullable<bool> IsYourLab24HourOpen { get; set; }
        public Nullable<bool> InternetAccess { get; set; }
        public Nullable<decimal> TotalFloorArea { get; set; }
        public Nullable<System.DateTime> DateOfInternalAudit { get; set; }
        public Nullable<System.DateTime> DateOfMgtReview { get; set; }
        public Nullable<System.DateTime> DateOfApplicationCompletion { get; set; }
        public string Street { get; set; }
        public string Locality { get; set; }
        public string City { get; set; }
        public string District { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string Pincode { get; set; }
        public string Website { get; set; }
        public Nullable<bool> TermAndCond { get; set; }
    
        public virtual Application Application { get; set; }
    }
}
