//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class MLPLaboratoryPersonal
    {
        public int ID { get; set; }
        public Nullable<int> ApplicationID { get; set; }
        public string ProficiencyTestProgram { get; set; }
        public Nullable<bool> Monday { get; set; }
        public Nullable<bool> Tuesday { get; set; }
        public Nullable<bool> Wednesday { get; set; }
        public Nullable<bool> Thursday { get; set; }
        public Nullable<bool> Friday { get; set; }
        public Nullable<bool> Saturday { get; set; }
        public Nullable<bool> Sunday { get; set; }
        public Nullable<bool> IsLab24HourOpen { get; set; }
        public string WorkingHourFrom { get; set; }
        public string WorkingHourTo { get; set; }
        public Nullable<bool> InternetAccess { get; set; }
        public Nullable<decimal> TotalFloor { get; set; }
    }
}
