//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModalityValue
    {
        public int ID { get; set; }
        public int ModalityID { get; set; }
        public bool Value { get; set; }
        public int ApplicationID { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual Modality Modality { get; set; }
    }
}
