//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class MostFrequentData
    {
        public int ID { get; set; }
        public int ApplicationID { get; set; }
        public string Type { get; set; }
        public string First { get; set; }
        public string Second { get; set; }
        public string Third { get; set; }
        public string Fourth { get; set; }
        public string Fifth { get; set; }
        public string Sixth { get; set; }
        public string Seventh { get; set; }
        public string Eighth { get; set; }
        public string Ninth { get; set; }
        public string Tenth { get; set; }
    
        public virtual Application Application { get; set; }
    }
}
