//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class MVTFApplication
    {
        public int ID { get; set; }
        public int ApplicationID { get; set; }
        public string Name { get; set; }
        public string Location { get; set; }
        public string Otherslocation { get; set; }
        public string Ownership { get; set; }
        public string OthersOwnership { get; set; }
        public string RegNo { get; set; }
        public string Authority { get; set; }
        public Nullable<System.DateTime> RegDate { get; set; }
        public Nullable<System.DateTime> YearOfEstablishment { get; set; }
        public Nullable<bool> LocalBranch { get; set; }
        public Nullable<bool> OverseasBranch { get; set; }
        public Nullable<bool> Is24HourOpen { get; set; }
        public Nullable<bool> InternetAccess { get; set; }
        public string PANNo { get; set; }
        public string TANNo { get; set; }
        public string OfficeBuildingType { get; set; }
        public Nullable<bool> BasicFacilities { get; set; }
        public Nullable<bool> WebisteAvailability { get; set; }
        public string Website { get; set; }
        public Nullable<System.DateTime> DateOfInternalAudit { get; set; }
        public Nullable<System.DateTime> DateOfMgmtReview { get; set; }
        public Nullable<System.DateTime> DateOfApplication { get; set; }
        public string Street1 { get; set; }
        public string Locality1 { get; set; }
        public string City1 { get; set; }
        public string District1 { get; set; }
        public string State1 { get; set; }
        public string Country1 { get; set; }
        public string Pincode1 { get; set; }
        public string LandMark1 { get; set; }
        public string Street2 { get; set; }
        public string Locality2 { get; set; }
        public string City2 { get; set; }
        public string District2 { get; set; }
        public string State2 { get; set; }
        public string Country2 { get; set; }
        public string Pincode2 { get; set; }
        public string LandMark2 { get; set; }
        public Nullable<bool> AddressSimilarity { get; set; }
        public string WorkingHoursFrom { get; set; }
        public string WorkingHoursTo { get; set; }
        public string WorkingDays { get; set; }
        public Nullable<bool> TandCCheck { get; set; }
    }
}
