//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class MVTFOrganisationChart
    {
        public int ID { get; set; }
        public int ApplicationID { get; set; }
        public string FileName { get; set; }
        public string FileURL { get; set; }
        public Nullable<int> TotalEmp { get; set; }
        public Nullable<int> FullTimeStaff { get; set; }
        public Nullable<int> PartTimeStaff { get; set; }
        public Nullable<int> TranslatorNo { get; set; }
    }
}
