//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class MVTFFacility
    {
        public int ID { get; set; }
        public int ApplicationID { get; set; }
        public string Treatment { get; set; }
        public string AddServices { get; set; }
        public string DocumentedPolicy { get; set; }
        public string Arrangements { get; set; }
        public string Agency { get; set; }
        public string TransAuthority { get; set; }
        public string OtherAuthority { get; set; }
    
        public virtual MVTFFacility MVTFFacilities1 { get; set; }
        public virtual MVTFFacility MVTFFacility1 { get; set; }
    }
}
