//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class MVTFGeneralPolicy
    {
        public int ID { get; set; }
        public int ApplicationID { get; set; }
        public string Principle { get; set; }
        public string OtherPrinciple { get; set; }
        public string Factors { get; set; }
        public string OtherFactors { get; set; }
        public string PaymentMode { get; set; }
        public string Quotation { get; set; }
        public string Package { get; set; }
        public string Directly { get; set; }
        public string Indirectly { get; set; }
        public string OtherMode { get; set; }
        public string Feedback { get; set; }
        public string Audit { get; set; }
        public string AuditDetails { get; set; }
        public string Review { get; set; }
    }
}
