//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class MVTFPrivacy
    {
        public int ID { get; set; }
        public int ApplicationID { get; set; }
        public Nullable<bool> Confidentiality { get; set; }
        public Nullable<bool> Liabilities { get; set; }
        public Nullable<bool> Disclaimer { get; set; }
        public Nullable<bool> Insurance { get; set; }
        public Nullable<bool> Policy { get; set; }
    }
}
