//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class NabhStandardRequirement
    {
        public int ID { get; set; }
        public string ClauseNo { get; set; }
        public string NabhStandardReq { get; set; }
        public Nullable<System.DateTime> DraftDate { get; set; }
    }
}
