//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class NabhEventMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NabhEventMaster()
        {
            this.ShortForAssessorTrannings = new HashSet<ShortForAssessorTranning>();
        }
    
        public int ID { get; set; }
        public string EventType { get; set; }
        public string EventCat { get; set; }
        public string EventCatDes { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShortForAssessorTranning> ShortForAssessorTrannings { get; set; }
    }
}
