//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class NABHStandard
    {
        public int ID { get; set; }
        public string Image { get; set; }
        public string StandardName { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<int> AppearanceOrder { get; set; }
        public string Applicationtype { get; set; }
        public string stdOrder { get; set; }
        public string StandardFile { get; set; }
        public string Guidebook { get; set; }
        public string Annexure { get; set; }
    }
}
