//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class NabhEvent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NabhEvent()
        {
            this.EventAddresses = new HashSet<EventAddress>();
            this.CertBackgrounds = new HashSet<CertBackground>();
        }
    
        public int ID { get; set; }
        public string EventType { get; set; }
        public string EventCat { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Fee { get; set; }
        public Nullable<System.DateTime> FrmDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string FrmTime { get; set; }
        public string ToTime { get; set; }
        public string EventLocation { get; set; }
        public Nullable<bool> Paid { get; set; }
        public string TransactionID { get; set; }
        public string Noofseats { get; set; }
        public string Remarks { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventAddress> EventAddresses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CertBackground> CertBackgrounds { get; set; }
    }
}
