//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class NetBankingPaymentDetail
    {
        public int ID { get; set; }
        public Nullable<int> AppID { get; set; }
        public Nullable<int> EventOrderID { get; set; }
        public Nullable<int> JournalOrderID { get; set; }
        public Nullable<int> StandardOrderID { get; set; }
        public string TransactionStatus { get; set; }
        public string TransactionRefNo { get; set; }
        public string TransactionBankCode { get; set; }
        public string TransactionID { get; set; }
        public string TransactionAmount { get; set; }
        public string TransactionDate { get; set; }
        public string Type { get; set; }
        public string TransactionStatusCode { get; set; }
        public string TransactionErrroMsg { get; set; }
        public string RequestToken { get; set; }
        public string DisNo { get; set; }
    }
}
