//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewAssessorNonComplianceObservation
    {
        public int ID { get; set; }
        public int AssignmentID { get; set; }
        public int AssessorID { get; set; }
        public int ApplicationID { get; set; }
        public int AssessmentTypeID { get; set; }
        public int SATID { get; set; }
        public string NCObservation { get; set; }
        public string Remarks { get; set; }
        public string Score { get; set; }
        public Nullable<bool> Saveedit { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> Createdon { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    }
}
