//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class NursingStaffDetail
    {
        public int ID { get; set; }
        public int ApplicationId { get; set; }
        public string StaffName { get; set; }
        public string DeptPosted { get; set; }
        public string RegNo { get; set; }
        public string CouncilName { get; set; }
    }
}
