//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class NursingClinicalValue
    {
        public int ID { get; set; }
        public Nullable<int> ApplicationID { get; set; }
        public Nullable<int> SpecialityID { get; set; }
        public Nullable<bool> ServiceProvided { get; set; }
        public Nullable<int> BedsAllocated { get; set; }
        public Nullable<int> Staff { get; set; }
    }
}
