//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class otherHCODetail
    {
        public int id { get; set; }
        public Nullable<int> applicantID { get; set; }
        public string phone { get; set; }
        public string emailId { get; set; }
        public string address { get; set; }
        public string latitude { get; set; }
        public string longitude { get; set; }
        public string scopeUrl { get; set; }
        public string pincode { get; set; }
        public string ScopeOfServices { get; set; }
        public string ClinicalServices { get; set; }
        public Nullable<System.DateTime> lastUpdateDate { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> sanctioned_beds { get; set; }
        public Nullable<int> operational_beds { get; set; }
        public Nullable<int> icu_beds { get; set; }
    
        public virtual HCOApplicantList HCOApplicantList { get; set; }
    }
}
