//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class OTPgenerateForClaim
    {
        public int id { get; set; }
        public string code { get; set; }
        public int userid { get; set; }
        public bool IsUsed { get; set; }
        public System.DateTime createOn { get; set; }
        public System.DateTime ValidTill { get; set; }
        public string verificationType { get; set; }
    }
}
