//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Panchakarmaapplication
    {
        public int ID { get; set; }
        public int ApplicationID { get; set; }
        public string Name { get; set; }
        public string certification { get; set; }
        public string renewalno { get; set; }
        public string website { get; set; }
        public string Hospitallocation { get; set; }
        public string OwnershipType { get; set; }
        public string Ownership { get; set; }
        public Nullable<System.DateTime> YearOfEstablishment { get; set; }
        public string Authority { get; set; }
        public Nullable<System.DateTime> YearOfOperationStarted { get; set; }
        public string Litigation { get; set; }
        public Nullable<System.DateTime> SelfAssessmentDoneOn { get; set; }
        public Nullable<System.DateTime> ImplementationCompletedOn { get; set; }
        public Nullable<bool> TandCCheck { get; set; }
        public Nullable<System.DateTime> ApplicationCompletedOn { get; set; }
        public string Street { get; set; }
        public string Locality { get; set; }
        public string City { get; set; }
        public string District { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string Pincode { get; set; }
    
        public virtual Application Application { get; set; }
    }
}
