//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class PanchkarmaBedInformation
    {
        public int ID { get; set; }
        public Nullable<int> ApplicationID { get; set; }
        public Nullable<int> MaleProcedureroom { get; set; }
        public Nullable<int> FemaleProcedureRoom { get; set; }
        public Nullable<int> TotalProcedureRoom { get; set; }
        public Nullable<int> MaleObservationRoom { get; set; }
        public Nullable<int> FemaleObservationRoom { get; set; }
        public Nullable<int> TotalObservationRoom { get; set; }
        public string TreatmentAvailability { get; set; }
        public string TreatmentType { get; set; }
    }
}
