//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentTransactionDetail
    {
        public int ID { get; set; }
        public string ResErrorText { get; set; }
        public string ResPaymentId { get; set; }
        public string ResTrackID { get; set; }
        public string ResErrorNo { get; set; }
        public string ResResult { get; set; }
        public string ResPosdate { get; set; }
        public string ResTranId { get; set; }
        public string ResAuth { get; set; }
        public string ResAVR { get; set; }
        public string ResRef { get; set; }
        public string ResAmount { get; set; }
        public string Resudf1 { get; set; }
        public string Resudf2 { get; set; }
        public string Resudf3 { get; set; }
        public string Resudf4 { get; set; }
        public string Resudf5 { get; set; }
        public Nullable<int> PaymentID { get; set; }
    }
}
