//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PaymentDetail()
        {
            this.tblSubUTRNumbers = new HashSet<tblSubUTRNumber>();
        }
    
        public int ID { get; set; }
        public int ApplicationID { get; set; }
        public string PaymentMode { get; set; }
        public string TransactionID { get; set; }
        public string DDNumber { get; set; }
        public string UTRNumber { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string IssuingBankName { get; set; }
        public string DetailOfBankVoucher { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> PaymentType { get; set; }
        public Nullable<int> size { get; set; }
        public string AttachmentName { get; set; }
        public string AttachmentPath { get; set; }
        public string GSTavail { get; set; }
        public string GSTNo { get; set; }
        public string LegalName { get; set; }
        public string TANNo { get; set; }
        public string PANNo { get; set; }
        public string Filename { get; set; }
        public string FilPath { get; set; }
        public string filename2 { get; set; }
        public string filpath2 { get; set; }
        public string PINo { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
    
        public virtual Application Application { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSubUTRNumber> tblSubUTRNumbers { get; set; }
    }
}
