//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHCApplication
    {
        public int ID { get; set; }
        public Nullable<int> ApplicationID { get; set; }
        public Nullable<bool> IsPHC { get; set; }
        public Nullable<bool> SupportiveFacilities { get; set; }
        public string Street { get; set; }
        public string Locality { get; set; }
        public string City { get; set; }
        public string District { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string Pincode { get; set; }
        public string website { get; set; }
        public string LocationNameofPHC { get; set; }
        public Nullable<bool> Is24x7 { get; set; }
        public Nullable<bool> FRURecognized { get; set; }
        public Nullable<System.DateTime> DataCollectionDate { get; set; }
        public string DataCollector { get; set; }
        public Nullable<System.DateTime> ImplementationCompletedOn { get; set; }
        public Nullable<bool> TandCCheck { get; set; }
        public Nullable<System.DateTime> ApplicationCompletedOn { get; set; }
    
        public virtual Application Application { get; set; }
    }
}
