//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHCService
    {
        public int ID { get; set; }
        public Nullable<int> ApplicationID { get; set; }
        public Nullable<bool> OPD { get; set; }
        public Nullable<bool> Emergency { get; set; }
        public Nullable<bool> Referral { get; set; }
        public Nullable<bool> Inpatient { get; set; }
        public Nullable<int> NumofbedAvail { get; set; }
        public string BedOccupancyRate { get; set; }
        public Nullable<int> NumofInpatBed { get; set; }
        public Nullable<int> AverageNew { get; set; }
        public Nullable<int> AverageOld { get; set; }
        public Nullable<int> Noofsubcentres { get; set; }
    
        public virtual Application Application { get; set; }
    }
}
