//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class PMJAYApplication
    {
        public int ID { get; set; }
        public int ApplicationID { get; set; }
        public string Name { get; set; }
        public string Website { get; set; }
        public string HospitalLocation { get; set; }
        public Nullable<bool> IsLocationSplitted { get; set; }
        public string OtherLocation { get; set; }
        public string OwnershipType { get; set; }
        public string Ownership { get; set; }
        public Nullable<System.DateTime> YearOfEstablishment { get; set; }
        public string Authority { get; set; }
        public Nullable<System.DateTime> YearOperationStarted { get; set; }
        public string Registered { get; set; }
        public Nullable<int> NumberOfBeds { get; set; }
        public Nullable<bool> OutPatientUnitAccreditation { get; set; }
        public string Litigation { get; set; }
        public Nullable<System.DateTime> SelfAssessmentDoneOn { get; set; }
        public Nullable<System.DateTime> ImplementationCompletedOn { get; set; }
        public Nullable<bool> TandCCheck { get; set; }
        public Nullable<System.DateTime> ApplicationCompletedOn { get; set; }
        public string Street { get; set; }
        public string Locality { get; set; }
        public string City { get; set; }
        public string District { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string Pincode { get; set; }
        public string OutsourcedServices { get; set; }
        public Nullable<bool> JointReplacement { get; set; }
        public string OutSourcedServicesSuper { get; set; }
        public string SchemeType { get; set; }
        public Nullable<bool> isEmpWithABPmjay { get; set; }
        public string HFRID { get; set; }
    
        public virtual Application Application { get; set; }
    }
}
