//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class PmJayQuestion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PmJayQuestion()
        {
            this.PmJayValues = new HashSet<PmJayValue>();
        }
    
        public int Id { get; set; }
        public string Element { get; set; }
        public bool IsDocRequired { get; set; }
        public string Options { get; set; }
        public bool AllowMultile { get; set; }
        public string GroupTitle { get; set; }
        public string GroupHead { get; set; }
        public Nullable<bool> Others { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PmJayValue> PmJayValues { get; set; }
    }
}
