//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreAssessmentReport
    {
        public int ID { get; set; }
        public Nullable<int> ApplicationID { get; set; }
        public Nullable<int> SubmittedBy { get; set; }
        public Nullable<bool> Accepted { get; set; }
        public string CorrectiveActionsReport { get; set; }
        public Nullable<bool> CorrectionReportAcceptance { get; set; }
        public Nullable<int> AcceptorID { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
