//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreAssessmentReportValue
    {
        public int ID { get; set; }
        public Nullable<int> ApplicationID { get; set; }
        public Nullable<int> AssessmentTypeID { get; set; }
        public Nullable<int> AssessorID { get; set; }
        public string ContactedPerson { get; set; }
        public string CorrectiveAction { get; set; }
        public string LatestManul { get; set; }
        public string DocumentAccreditation { get; set; }
        public string Summary { get; set; }
        public Nullable<int> NoOfAssessor { get; set; }
        public Nullable<int> NoOfDays { get; set; }
        public string AssessmentSplitStatus { get; set; }
        public string AssessmentSplitExplain { get; set; }
        public string AssessmentCorrectiveStatus { get; set; }
        public string AssessmentCorrectiveRemarks { get; set; }
        public string Recommendation { get; set; }
        public Nullable<bool> saveedit { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual AssessmentType AssessmentType { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
