//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcesssAssessorClaimFormLog
    {
        public int Id { get; set; }
        public int claimId { get; set; }
        public int AssignedTo { get; set; }
        public string Remark { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    
        public virtual AssessorClaimStatu AssessorClaimStatu { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
