//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Professional
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Professional()
        {
            this.MitraProfessionalsEnclosures = new HashSet<MitraProfessionalsEnclosure>();
        }
    
        public int ProfessionalID { get; set; }
        public Nullable<int> ApplicationID { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Designation { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Phone { get; set; }
        public string EmailID { get; set; }
        public string ProofOfIdentification { get; set; }
        public string EducationalQualification { get; set; }
        public string SpecializedDegree { get; set; }
        public Nullable<int> TotalWorkExperience { get; set; }
        public Nullable<int> NABHImplementationExperience { get; set; }
        public Nullable<bool> NABHPOIattended { get; set; }
        public string NABHPOIStandards { get; set; }
        public Nullable<bool> IsCurrentNABHAssessor { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string ProfGovtIdType { get; set; }
        public Nullable<int> HospitalITExperience { get; set; }
        public Nullable<int> HISExperience { get; set; }
        public Nullable<int> ITInfraExperience { get; set; }
        public Nullable<int> AdvisoryExperience { get; set; }
    
        public virtual MitraApplication MitraApplication { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MitraProfessionalsEnclosure> MitraProfessionalsEnclosures { get; set; }
    }
}
