//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfilesAccessRightsLink
    {
        public int ID { get; set; }
        public int ProfileID { get; set; }
        public int AccessRightID { get; set; }
    
        public virtual AccessRight AccessRight { get; set; }
        public virtual Profile Profile { get; set; }
    }
}
