//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgramOfficer
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string EmailID { get; set; }
        public Nullable<int> Ext { get; set; }
        public string ApplicationTypeID { get; set; }
        public string AccProcess { get; set; }
        public Nullable<bool> Acknowledgement { get; set; }
    }
}
