//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectUserDetail
    {
        public int ID { get; set; }
        public int ApplicationID { get; set; }
        public string HospitalName { get; set; }
        public string Street { get; set; }
        public string Locality { get; set; }
        public string District { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string website { get; set; }
        public string Pincode { get; set; }
        public int BedSanctioned { get; set; }
        public string Title1 { get; set; }
        public string Name1 { get; set; }
        public string Designation1 { get; set; }
        public string Telephone1 { get; set; }
        public string Mobile1 { get; set; }
        public string Fax1 { get; set; }
        public string Email1 { get; set; }
        public string Title2 { get; set; }
        public string Name2 { get; set; }
        public string Designation2 { get; set; }
        public string Telephone2 { get; set; }
        public string Mobile2 { get; set; }
        public string Fax2 { get; set; }
        public string Email2 { get; set; }
        public string OtherContactInfo { get; set; }
    
        public virtual ProjectApplication ProjectApplication { get; set; }
    }
}
