//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class QAPApplication
    {
        public int ID { get; set; }
        public Nullable<int> ApplicationID { get; set; }
        public string CenterName { get; set; }
        public string StateGovtName { get; set; }
        public string StateCoordName { get; set; }
        public string Street { get; set; }
        public string Locality { get; set; }
        public string City { get; set; }
        public string District { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string Pincode { get; set; }
        public int YearOfEstablishment { get; set; }
        public Nullable<int> Beds { get; set; }
        public Nullable<System.DateTime> ApplicationCompletedOn { get; set; }
        public Nullable<int> statecordTel { get; set; }
        public Nullable<int> statecordMob { get; set; }
        public string statecordEmail { get; set; }
        public string statecordAdd { get; set; }
        public string website { get; set; }
    
        public virtual Application Application { get; set; }
    }
}
