//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class QualityAndsafetyChecklistclinic
    {
        public int id { get; set; }
        public int parentId { get; set; }
        public int applicationTyped { get; set; }
        public string text { get; set; }
    }
}
