//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReviewMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReviewMaster()
        {
            this.ReviewRemarks = new HashSet<ReviewRemark>();
        }
    
        public int ID { get; set; }
        public string Requirement { get; set; }
        public string GroupTitle { get; set; }
        public string valuetype { get; set; }
        public Nullable<int> ApplicationTypeID { get; set; }
    
        public virtual ApplicationType ApplicationType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReviewRemark> ReviewRemarks { get; set; }
    }
}
