//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReviewRemark
    {
        public int ID { get; set; }
        public Nullable<int> ReviewMasterID { get; set; }
        public Nullable<int> ApplicationID { get; set; }
        public Nullable<int> AssessmentID { get; set; }
        public Nullable<int> AssesserID { get; set; }
        public Nullable<bool> Observation { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> saveedit { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual AssessmentType AssessmentType { get; set; }
        public virtual ReviewMaster ReviewMaster { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
