//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScopeByAssessor
    {
        public int ID { get; set; }
        public Nullable<int> ApplicationID { get; set; }
        public Nullable<int> ScopeID { get; set; }
        public Nullable<bool> Provided { get; set; }
        public Nullable<int> SaveEdit { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<bool> Human_Resource_Adequate { get; set; }
        public Nullable<bool> Infrastructure_Adequate { get; set; }
        public Nullable<int> Asstypeid { get; set; }
    }
}
