//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scope
    {
        public int Id { get; set; }
        public string Broad_Scope { get; set; }
        public string Sub_Speciality_Desc { get; set; }
        public string Sub_Speciality_Code { get; set; }
    }
}
