//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScopeOfAccreditation
    {
        public int id { get; set; }
        public Nullable<int> serviceid { get; set; }
        public Nullable<int> applicationid { get; set; }
        public string serviceprovided { get; set; }
        public string averagedailyOut { get; set; }
        public string averagedailyIN { get; set; }
        public Nullable<int> NumberOfConsultants { get; set; }
        public string speciality { get; set; }
    }
}
