//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScopeSpeciality
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ScopeSpeciality()
        {
            this.DentalEquipments = new HashSet<DentalEquipment>();
            this.DentalLabDatas = new HashSet<DentalLabData>();
            this.HospitalNumberOfBeds = new HashSet<HospitalNumberOfBed>();
            this.InpatientCares = new HashSet<InpatientCare>();
            this.OtherServicesValues = new HashSet<OtherServicesValue>();
            this.ScopeCertificationValues = new HashSet<ScopeCertificationValue>();
            this.ScopeServiceValues = new HashSet<ScopeServiceValue>();
            this.tblAyurveda_Clinical = new HashSet<tblAyurveda_Clinical>();
            this.ScopeValues = new HashSet<ScopeValue>();
        }
    
        public int ID { get; set; }
        public string Speciality { get; set; }
        public int ApplicationType { get; set; }
        public string GroupTitle { get; set; }
        public string GroupHead { get; set; }
        public Nullable<bool> Others { get; set; }
    
        public virtual ApplicationType ApplicationType1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DentalEquipment> DentalEquipments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DentalLabData> DentalLabDatas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HospitalNumberOfBed> HospitalNumberOfBeds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InpatientCare> InpatientCares { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OtherServicesValue> OtherServicesValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScopeCertificationValue> ScopeCertificationValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScopeServiceValue> ScopeServiceValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAyurveda_Clinical> tblAyurveda_Clinical { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScopeValue> ScopeValues { get; set; }
    }
}
