//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScopeCertificationValue
    {
        public int Id { get; set; }
        public Nullable<int> SpecialityID { get; set; }
        public Nullable<int> ApplicationID { get; set; }
        public Nullable<bool> ServiceProvided { get; set; }
        public string OP_Type { get; set; }
        public string IP_Type { get; set; }
        public string Emergency_Availability { get; set; }
        public string ConsultantName { get; set; }
        public string EngagementType { get; set; }
        public string Graduation { get; set; }
        public string PostGraduation { get; set; }
        public string SuperSpecialization { get; set; }
        public string OtherCertification { get; set; }
        public string MedicalCouncil { get; set; }
        public string RegistrationNumber { get; set; }
        public string DepartmentSpecificEquipment { get; set; }
        public string UHIDs { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual ScopeSpeciality ScopeSpeciality { get; set; }
    }
}
