//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScoreSheetMasterOtherValue
    {
        public int Id { get; set; }
        public int ParentId { get; set; }
        public string TestForYes { get; set; }
        public string TestForNo { get; set; }
        public string Description { get; set; }
    }
}
