//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScoreSheetMaster
    {
        public int ID { get; set; }
        public string Element { get; set; }
        public int ParentElement { get; set; }
        public int ApplicationType { get; set; }
        public string SheetPath { get; set; }
        public Nullable<byte> SelectionFlag { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
    }
}
