//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecretariatMemberDocument
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string FileDescription { get; set; }
        public string FileName { get; set; }
        public string FileURL { get; set; }
    }
}
