//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class SelfAssessmentToolkit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SelfAssessmentToolkit()
        {
            this.SelfAssessmentAttachments = new HashSet<SelfAssessmentAttachment>();
            this.SelfAssessmentOtherValues = new HashSet<SelfAssessmentOtherValue>();
            this.SelfAssessmentValues = new HashSet<SelfAssessmentValue>();
        }
    
        public int ID { get; set; }
        public string Element { get; set; }
        public int ParentElement { get; set; }
        public int ApplicationType { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> AppearanceOrder { get; set; }
        public string RefCode { get; set; }
        public Nullable<int> Version { get; set; }
        public string color { get; set; }
        public string level { get; set; }
        public string ScoreOption { get; set; }
        public string Guidance { get; set; }
    
        public virtual ApplicationType ApplicationType1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SelfAssessmentAttachment> SelfAssessmentAttachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SelfAssessmentOtherValue> SelfAssessmentOtherValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SelfAssessmentValue> SelfAssessmentValues { get; set; }
    }
}
