//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class SelfAssessmentAttachment
    {
        public int ID { get; set; }
        public int ApplicationID { get; set; }
        public int UserID { get; set; }
        public int SATID { get; set; }
        public string Reference { get; set; }
        public string PathAdd { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual SelfAssessmentToolkit SelfAssessmentToolkit { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
