//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class SelfAssessmentOtherValue
    {
        public int Id { get; set; }
        public int SATID { get; set; }
        public int ApplicationID { get; set; }
        public int Implementation { get; set; }
        public int System { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual SelfAssessmentToolkit SelfAssessmentToolkit { get; set; }
    }
}
