//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class shco_app
    {
        public int id { get; set; }
        public Nullable<int> applicationid { get; set; }
        public string accreditation { get; set; }
        public string reaccreditation { get; set; }
        public string cyclenumber { get; set; }
        public string locationofshco { get; set; }
        public string splitlocation { get; set; }
        public string splitlocationval { get; set; }
        public string otherownershiplegalidentity { get; set; }
        public string legalval { get; set; }
        public string whichauthority { get; set; }
    
        public virtual Application Application { get; set; }
    }
}
