//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShortForAssessorTranning
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int EventCatId { get; set; }
        public bool IsShortListed { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        public virtual NabhEventMaster NabhEventMaster { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
