//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffInformationEye
    {
        public int ID { get; set; }
        public string StaffGroup { get; set; }
        public Nullable<int> GroupParent { get; set; }
        public Nullable<int> ApplicationType { get; set; }
        public bool Others { get; set; }
    
        public virtual ApplicationType ApplicationType1 { get; set; }
    }
}
