//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffInformationValue
    {
        public int ID { get; set; }
        public int ApplicationID { get; set; }
        public int StaffInformationID { get; set; }
        public int Number { get; set; }
        public string Remarks { get; set; }
        public string Name { get; set; }
        public string Designation { get; set; }
        public string Department { get; set; }
        public string regularOPD { get; set; }
        public string Qualification { get; set; }
        public string NameRegCouncil { get; set; }
        public string RegNo { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual StaffInformation StaffInformation { get; set; }
    }
}
