//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffInformation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StaffInformation()
        {
            this.StaffInformationValues = new HashSet<StaffInformationValue>();
            this.StaffInformationValueEyes = new HashSet<StaffInformationValueEye>();
        }
    
        public int ID { get; set; }
        public string StaffGroup { get; set; }
        public Nullable<int> GroupParent { get; set; }
        public Nullable<int> ApplicationType { get; set; }
        public bool Others { get; set; }
        public Nullable<int> Seq_No { get; set; }
    
        public virtual ApplicationType ApplicationType1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StaffInformationValue> StaffInformationValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StaffInformationValueEye> StaffInformationValueEyes { get; set; }
    }
}
