//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffInformation_BB
    {
        public int ID { get; set; }
        public int ApplicationID { get; set; }
        public string Name { get; set; }
        public string Designation { get; set; }
        public string Qualification { get; set; }
        public Nullable<decimal> Experience { get; set; }
        public string filename { get; set; }
        public string filepath { get; set; }
    
        public virtual Application Application { get; set; }
    }
}
