//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class StandardInventory
    {
        public int StandardId { get; set; }
        public string TotalStock { get; set; }
        public string AddStock { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public string Soldout { get; set; }
        public Nullable<System.DateTime> Solddate { get; set; }
        public string Remark { get; set; }
        public int Id { get; set; }
        public string Filepath { get; set; }
    }
}
