//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblassessorprofilepic
    {
        public int id { get; set; }
        public Nullable<int> userid { get; set; }
        public string picpath { get; set; }
        public string filename { get; set; }
        public string undertakinpath { get; set; }
        public string degreepath { get; set; }
        public string regcertpath { get; set; }
        public string govidpath { get; set; }
        public string Vregformpath { get; set; }
        public string nabhcertpath { get; set; }
        public string biopath { get; set; }
    }
}
