//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAssessorTrainingNominatedBy
    {
        public int id { get; set; }
        public string name { get; set; }
        public string Designation { get; set; }
        public string Organization { get; set; }
        public string Phoneno { get; set; }
        public string EmailID { get; set; }
        public Nullable<int> AssessorTrainingId { get; set; }
        public string nomName { get; set; }
        public string nomDesignation { get; set; }
        public string nomOrganization { get; set; }
        public string nomPhoneno { get; set; }
        public string nomEmailID { get; set; }
    }
}
