//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblApiKey
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblApiKey()
        {
            this.ApiPermissions = new HashSet<ApiPermission>();
        }
    
        public int ApiKeyId { get; set; }
        public int ApiUserId { get; set; }
        public string KeyName { get; set; }
        public string ApiKey { get; set; }
        public string ApiSecretHash { get; set; }
        public bool IsRevoked { get; set; }
        public Nullable<System.DateTime> ExpiresOn { get; set; }
        public Nullable<System.DateTime> LastUsedOn { get; set; }
        public System.DateTime CreatedOn { get; set; }
    
        public virtual ApiUser ApiUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApiPermission> ApiPermissions { get; set; }
    }
}
