//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAyurveda_Clinical
    {
        public int id { get; set; }
        public Nullable<int> specialityid { get; set; }
        public Nullable<int> applicationid { get; set; }
        public Nullable<int> applicationtype { get; set; }
        public Nullable<bool> serviceprovided { get; set; }
        public Nullable<int> numberofbeds { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual ApplicationType ApplicationType1 { get; set; }
        public virtual ScopeSpeciality ScopeSpeciality { get; set; }
    }
}
