//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAgreemantDetail
    {
        public int Id { get; set; }
        public Nullable<int> ApplicationID { get; set; }
        public string Date { get; set; }
        public string DirName { get; set; }
        public string Witness1 { get; set; }
        public string Witness2 { get; set; }
        public Nullable<System.DateTime> createdon { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string Email2 { get; set; }
        public string Mobile2 { get; set; }
    }
}
