//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblApiRequestLog
    {
        public long Id { get; set; }
        public Nullable<int> ApiUserId { get; set; }
        public Nullable<int> ApiKeyId { get; set; }
        public string Endpoint { get; set; }
        public string HttpMethod { get; set; }
        public string IpAddress { get; set; }
        public Nullable<int> StatusCode { get; set; }
        public System.DateTime RequestDate { get; set; }
    
        public virtual ApiUser ApiUser { get; set; }
    }
}
