//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAudit
    {
        public int AuditID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Information { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
    }
}
