//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblContactDetail
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Designation { get; set; }
        public string EmailID { get; set; }
        public Nullable<int> ExtNo { get; set; }
        public Nullable<int> AppearanceOrder { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Program { get; set; }
        public string Telephone1 { get; set; }
        public string Telephone2 { get; set; }
        public string Telephone { get; set; }
    }
}
