//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEfile
    {
        public int Id { get; set; }
        public string filename { get; set; }
        public string remark { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string email { get; set; }
        public string PoName { get; set; }
        public string Type { get; set; }
        public string FileFrom { get; set; }
        public string FileType { get; set; }
        public string AppType { get; set; }
        public string FileStatus { get; set; }
    }
}
