//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInfectionCtrl
    {
        public int ID { get; set; }
        public int ApplicationID { get; set; }
        public string sterlization { get; set; }
        public string Autoclaving { get; set; }
        public string Glass_bead_sterilizer { get; set; }
        public string UV_chamber { get; set; }
        public string Surface_disinfectant { get; set; }
        public string Laundry { get; set; }
        public string Disposable { get; set; }
        public string Washing { get; set; }
        public string Remarks { get; set; }
    }
}
