//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInfectionCtrlvalue
    {
        public int ID { get; set; }
        public int ApplicationID { get; set; }
        public string sterlization { get; set; }
        public Nullable<bool> Autoclaving { get; set; }
        public Nullable<bool> Glass_bead_sterilizer { get; set; }
        public Nullable<bool> UV_chamber { get; set; }
        public Nullable<bool> Surface_disinfectant { get; set; }
        public Nullable<bool> Laundry { get; set; }
        public Nullable<bool> Disposable { get; set; }
        public Nullable<bool> Washing { get; set; }
        public string Remarks { get; set; }
    }
}
