//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProjectDept
    {
        public int ID { get; set; }
        public string DeptName { get; set; }
        public string DeptPoints { get; set; }
        public int ProjectType { get; set; }
        public string GroupTitle { get; set; }
    }
}
