//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReference
    {
        public int ReferenceID { get; set; }
        public Nullable<int> ApplicationID { get; set; }
        public string Name { get; set; }
        public string Designation { get; set; }
        public string Organisation { get; set; }
        public string EmailID { get; set; }
        public string Phone { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    
        public virtual MitraApplication MitraApplication { get; set; }
    }
}
