//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTrainingfeedback
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public string Program { get; set; }
        public string Schedule { get; set; }
        public string City { get; set; }
        public string Ovjectives { get; set; }
        public int Rating { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string FullName { get; set; }
        public string OrganizationName { get; set; }
        public string MobileNo { get; set; }
        public string EmailID { get; set; }
        public string EvaluationType { get; set; }
    }
}
