//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblUser()
        {
            this.ApplicationCurrentStatus = new HashSet<ApplicationCurrentStatu>();
            this.Applications = new HashSet<Application>();
            this.ApplicationStatusUpdatedByACMembers = new HashSet<ApplicationStatusUpdatedByACMember>();
            this.AssessorAssignments = new HashSet<AssessorAssignment>();
            this.AssessorAvailabilities = new HashSet<AssessorAvailability>();
            this.AssessorCertificates = new HashSet<AssessorCertificate>();
            this.AssessorQualifications = new HashSet<AssessorQualification>();
            this.AssessorsRemarks = new HashSet<AssessorsRemark>();
            this.AssignedAppTypesToUsers = new HashSet<AssignedAppTypesToUser>();
            this.DeficienciesReports = new HashSet<DeficienciesReport>();
            this.Feedbacks = new HashSet<Feedback>();
            this.FeedbackValues = new HashSet<FeedbackValue>();
            this.HCOBulkPaymentDetails = new HashSet<HCOBulkPaymentDetail>();
            this.InCs = new HashSet<InC>();
            this.NabhAttachments = new HashSet<NabhAttachment>();
            this.NabhAttachments1 = new HashSet<NabhAttachment>();
            this.PreAssessmentReportValues = new HashSet<PreAssessmentReportValue>();
            this.ProcesssAssessorClaimFormLogs = new HashSet<ProcesssAssessorClaimFormLog>();
            this.ProjectApplications = new HashSet<ProjectApplication>();
            this.QualityManualAssignedToAssessors = new HashSet<QualityManualAssignedToAssessor>();
            this.ReviewRemarks = new HashSet<ReviewRemark>();
            this.ReviewUpdates = new HashSet<ReviewUpdate>();
            this.SelfAssessmentAttachments = new HashSet<SelfAssessmentAttachment>();
            this.ShortForAssessorTrannings = new HashSet<ShortForAssessorTranning>();
            this.tblABDMFacilities = new HashSet<tblABDMFacility>();
            this.VisitorUniqueIDs = new HashSet<VisitorUniqueID>();
            this.UploadDocuments = new HashSet<UploadDocument>();
            this.VerifiedDocNumbers = new HashSet<VerifiedDocNumber>();
        }
    
        public int Userid { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int RoleID { get; set; }
        public bool Active { get; set; }
        public string Phone { get; set; }
        public Nullable<int> Extension { get; set; }
        public string Mobile { get; set; }
        public Nullable<int> EmployeeNumber { get; set; }
        public Nullable<int> PartnerID { get; set; }
        public Nullable<int> OrganisationID { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> TechAdmin { get; set; }
        public string Location { get; set; }
        public string PrimaryCompetence { get; set; }
        public string SecondaryCompetence { get; set; }
        public string PreferredAreaofCalling { get; set; }
        public string Experience { get; set; }
        public string AgewithCompany { get; set; }
        public string Residence { get; set; }
        public Nullable<int> ReportTo { get; set; }
        public string UserGroup { get; set; }
        public Nullable<System.DateTime> ExpDate { get; set; }
        public string Designation { get; set; }
        public string Department { get; set; }
        public string Category { get; set; }
        public string Speciality { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string OrganisationName { get; set; }
        public string OthersSpeciality { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string PinCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicationCurrentStatu> ApplicationCurrentStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Application> Applications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicationStatusUpdatedByACMember> ApplicationStatusUpdatedByACMembers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssessorAssignment> AssessorAssignments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssessorAvailability> AssessorAvailabilities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssessorCertificate> AssessorCertificates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssessorQualification> AssessorQualifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssessorsRemark> AssessorsRemarks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssignedAppTypesToUser> AssignedAppTypesToUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeficienciesReport> DeficienciesReports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Feedback> Feedbacks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FeedbackValue> FeedbackValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HCOBulkPaymentDetail> HCOBulkPaymentDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InC> InCs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NabhAttachment> NabhAttachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NabhAttachment> NabhAttachments1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PreAssessmentReportValue> PreAssessmentReportValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProcesssAssessorClaimFormLog> ProcesssAssessorClaimFormLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectApplication> ProjectApplications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QualityManualAssignedToAssessor> QualityManualAssignedToAssessors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReviewRemark> ReviewRemarks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReviewUpdate> ReviewUpdates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SelfAssessmentAttachment> SelfAssessmentAttachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShortForAssessorTranning> ShortForAssessorTrannings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblABDMFacility> tblABDMFacilities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VisitorUniqueID> VisitorUniqueIDs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UploadDocument> UploadDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VerifiedDocNumber> VerifiedDocNumbers { get; set; }
    }
}
