//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThreadComment
    {
        public int ID { get; set; }
        public Nullable<int> ThreadID { get; set; }
        public string Comment { get; set; }
        public Nullable<int> PostBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
