//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class TLDStaffInformation
    {
        public int id { get; set; }
        public string name { get; set; }
        public string designation { get; set; }
        public string qualification { get; set; }
        public string exprience { get; set; }
        public string TLDbatch { get; set; }
        public string applicationid { get; set; }
    }
}
