//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trainingcertificate
    {
        public int ID { get; set; }
        public Nullable<int> EventID { get; set; }
        public string CertNo { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<bool> Attendance { get; set; }
        public Nullable<bool> Verified { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string FileName { get; set; }
    }
}
