//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class UploadDocument
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public string FilePath { get; set; }
        public string FileName { get; set; }
        public int AssignmentID { get; set; }
    
        public virtual AssessorAssignment AssessorAssignment { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
