//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLock
    {
        public int L_ID { get; set; }
        public string L_Email { get; set; }
        public Nullable<System.DateTime> L_lockTime { get; set; }
    }
}
