//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class WellnessCenterApplication
    {
        public int ID { get; set; }
        public Nullable<int> ApplicationID { get; set; }
        public string Name { get; set; }
        public string Street { get; set; }
        public string Locality { get; set; }
        public string City { get; set; }
        public string District { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string Pincode { get; set; }
        public string website { get; set; }
        public string OwnershipType { get; set; }
        public Nullable<System.DateTime> YearOfEstablishment { get; set; }
        public Nullable<System.DateTime> YearOfFunctioning { get; set; }
        public string Profile { get; set; }
        public Nullable<decimal> Area { get; set; }
        public Nullable<int> ServiceStations { get; set; }
        public Nullable<bool> overnight { get; set; }
        public Nullable<bool> TandCCheck { get; set; }
        public Nullable<System.DateTime> ImplementationCompletedOn { get; set; }
        public Nullable<System.DateTime> ApplicationCompletedOn { get; set; }
        public string Scope { get; set; }
    
        public virtual Application Application { get; set; }
    }
}
